### ISSUE TITLE
DDS IDL interoperability with ROS 2 messages

### ISSUE THREAD

**Issue by YGD159** [eProsima/Fast-DDS#2603] opened 2022-03-25 08:31 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I want to try to use it to implement conversion of complex data type .
But I can't achieve it, it doesn't seem to recognize data types.
Can you give me some advice?
Yours support is greatly appreciated.

### Current behavior

![temp1](https://user-images.githubusercontent.com/52145923/160083718-bc5329c1-274c-4dcb-a497-e58d691457e4.png)
![temp](https://user-images.githubusercontent.com/52145923/160083726-6b22b856-f7c4-4068-83d7-b950f849015f.png)

### Steps to reproduce

You can use the demo to reproduce
`source /opt/eloquent/ros/setup.bash`
`RMW_IMPLEMENTATION=rmw_fastrtps_cpp colcon build`
[fastdds_record_typesupport.zip](https://github.com/eProsima/Fast-DDS/files/8348747/fastdds_record_typesupport.zip)

### Fast DDS version/commit

Fast-DDS 2.6

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

ubuntu18.04
ros2 : eloquent

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-25 09:26
Hi @YGD159,

Sorry for not being of help but this is not an issue with Fast DDS library. As you can see the issue is raised in the ROS 2 stack, specifically in `rosidl_generator_c` package. You should look into this package documentation or open the issue in its repository. However, it could be that what you are trying to do is not supported by ROS 2 as this [ROS 2 design document](https://design.ros2.org/articles/idl_interface_definition.html#preprocessing) says that there is no preprocessing of the `idl` files.

I will proceed therefore to close this issue.

**Closed by JLBuenoLopez-eProsima** 2022-03-25 09:26 UTC
Labels: triage

**Comment by YGD159** [comment] 2022-03-25 11:36
Anyway, thank you very much for your reply




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "José Luis Bueno ***@***.***&gt;; 
发送时间: 2022年3月25日(星期五) 下午5:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eProsima/Fast-DDS] DDS IDL interoperability with ROS 2 messages (Issue #2603)





 
Hi @YGD159,
 
Sorry for not being of help but this is not an issue with Fast DDS library. As you can see the issue is raised in the ROS 2 stack, specifically in rosidl_generator_c package. You should look into this package documentation or open the issue in its repository. However, it could be that what you are trying to do is not supported by ROS 2 as this ROS 2 design document says that there is no preprocessing of the idl files.
 
I will proceed therefore to close this issue.
