### ISSUE TITLE
tinyxml2  can not compiled

### ISSUE THREAD

**Issue by stilong** [eProsima/Fast-DDS#3322] opened 2023-02-23 07:22 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

complied

### Current behavior

lgh@vubuntu:~/ShapesDemo$ colcon build --cmake-args -DSECURITY=ON -DEPROSIMA_BUILD=ON -DTINYXML2_FROM_SOURCE=ON -DCMAKE_BUILD_TYPE=Debug --parallel-workers 32
Starting >>> fastcdr 
Starting >>> foonathan_memory_vendor
Finished <<< foonathan_memory_vendor [0.33s]                                                     
Finished <<< fastcdr [18.6s]                       
Starting >>> fastrtps
--- stderr: fastrtps                          
fatal: not a git repository (or any of the parent directories): .git
CMake Error at cmake/common/eprosima_libraries.cmake:228 (message):
  Cannot configure Git submodule TinyXML2
Call Stack (most recent call first):
  CMakeLists.txt:237 (eprosima_find_thirdparty)

---
Failed   <<< fastrtps [0.10s, exited with code 1]

Summary: 2 packages finished [19.1s]
  1 package failed: fastrtps
  1 package had stderr output: fastrtps
  1 package not processed

### Steps to reproduce

no

### Fast DDS version/commit

2.9.1

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by EduPonz** [comment] 2023-03-02 10:17
I'm closing this as duplicate of eProsima/ShapesDemo#71. I have included that answer to this ticket in that one.

**Closed by EduPonz** 2023-03-02 10:17 UTC
Labels: triage

**Comment by stilong** [comment] 2023-05-22 11:04
how can i read the byte array data from the instance of class DynamicData   .  
















At 2023-03-02 18:19:40, "Eduardo Ponz Segrelles" ***@***.***> wrote:

I'm closing this as duplicate of eProsima/ShapesDemo#71. I have included that answer to this ticket in that one.

**Comment by EduPonz** [comment] 2023-05-22 13:55
Hi @stilong,

For visibility's sake, could you please open the question as a separate ticket in the [Q&A forum](https://github.com/eProsima/Fast-DDS/discussions/categories/q-a)?
