### ISSUE TITLE
Changing Partition QoS on running Publisher and Subscriber has no affect [12315]

### ISSUE THREAD

**Issue by tobi4321** [eProsima/Fast-DDS#2107] opened 2021-07-30 16:40 UTC
I have a a Participant with different publishers and subscribers. The publishers have a initial partition, while the subscribers should change the partition on runtime. This should filter data on sending side. How can i solve this problem?

subscriber.set_qos() has no affect on running subscribers. Or is there a refresh mechanism i did not use?

**Comment by EduPonz** [comment] 2021-08-02 06:13
Hi @tobi4321 ,

I just tested changing the partitions of subscribers using the HelloWorld example and everything seems to be working as expected for me. What I did was:

* Test 1: Set publisher and subscriber in the same partition. Then, wait for some samples to be received, change the subscriber's partition, and check that the reception stopped.
* Test 2: Set publisher and subscriber in different partitions. Then, wait for some samples to be sent but not received. Finally, set the subscriber's partition to that of the publisher and check that data started to be received.

Can you provide some more information like what QoS settings are you using? In fact, some minimal example to reproduce would be much appreciated.

**Comment by tobi4321** [comment] 2021-08-02 06:45
Thanks for your response.
The Qos Settings im using are:

DomainParticipantQos:
`DomainParticipantQos participantQos;
 participantQos.wire_protocol().builtin.discovery_config.leaseDuration = eprosima::fastrtps::c_TimeInfinite;
 participantQos.name("Participant_LectorCom");
 participantQos.allocation().participants = eprosima::fastrtps::ResourceLimitedContainerConfig::fixed_size_configuration(10u);
 participantQos.allocation().writers = eprosima::fastrtps::ResourceLimitedContainerConfig::fixed_size_configuration(10u);
 participantQos.allocation().readers = eprosima::fastrtps::ResourceLimitedContainerConfig::fixed_size_configuration(10u);`

TopicQos: Default

PublisherQos:
` PublisherQos pfqos;
  pfqos.partition().push_back("MasterControl");`

DataWriterQos:
`DataWriterQos wqos;
  wqos.endpoint().history_memory_policy = DYNAMIC_REUSABLE_MEMORY_MODE;
  wqos.history().kind = KEEP_LAST_HISTORY_QOS;
  wqos.durability().kind = VOLATILE_DURABILITY_QOS;
  // if speed is to low, set to BEST_EFFORT_RELIABILITY_QOS
  wqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
  // depth must be lower than max_samples_per_instance
  wqos.history().depth = 1;
  wqos.writer_resource_limits().matched_subscriber_allocation = eprosima::fastrtps::ResourceLimitedContainerConfig::fixed_size_configuration(5u);`

SubscriberQos:
` SubscriberQos sqos;
  sqos.partition().push_back("MasterControl");`

DataReaderQos:
DataReaderQos rqos;
  rqos.endpoint().history_memory_policy = DYNAMIC_REUSABLE_MEMORY_MODE;
  rqos.history().kind = KEEP_LAST_HISTORY_QOS;
  rqos.durability().kind = VOLATILE_DURABILITY_QOS;
  // if speed is low, set to BEST_EFFORT_RELIABILITY_QOS
  rqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
  // depth must be lower than max_samples_per_isntance
  rqos.history().depth = 1;
  rqos.reader_resource_limits().matched_publisher_allocation = eprosima::fastrtps::ResourceLimitedContainerConfig::fixed_size_configuration(5u);


To Change the PartitionQos on Subscribing side im using the following method:
`bool MasterControlHandler::enableSubscribingTopic(bool pState)
{
  SubscriberQos sqos = m_masterControlSubscriber->get_qos();
  sqos.partition().set_max_size(5); //Setter function
  std::vector<std::string> partitions = sqos.partition().names();
  if(pState)
  {
  	partitions.push_back("MasterControl");	
  }
  else
  {
    std::remove(partitions.begin(),partitions.end(),"MasterControl");
  }
  sqos.partition().names(partitions);
  ReturnCode_t retcode = m_masterControlSubscriber->set_qos(sqos);
  if(retcode != ReturnCode_t::RETCODE_OK)
  {
	std::cout << "Error while changing partition qos on master control subscriber." << std::endl;
	return false;
  }
  return true;
}`

I think its possible, that a little peace of my code isnt working like expected. Hope the code snippets can help finding the problem.

**Comment by MiguelCompany** [comment] 2021-08-02 07:02
As you can see in the [standard docs](https://en.cppreference.com/w/cpp/algorithm/remove) example, calling `std::remove` will not erase the entry from the vector. You need to call `vector.erase` with the result.

Corrected code:

```
bool MasterControlHandler::enableSubscribingTopic(bool pState)
{
    SubscriberQos sqos = m_masterControlSubscriber->get_qos();
    sqos.partition().set_max_size(5);
    // Setter function
    std::vector<std::string> partitions = sqos.partition().names();
    if(pState)
    {
        partitions.push_back("MasterControl");
    }
    else
    {
        // Old, non-working code
        // std::remove(partitions.begin(),partitions.end(),"MasterControl");

        // Correct, working code
        partitions.erase(std::remove(partitions.begin(),partitions.end(),"MasterControl"), partitions.end());
    }
    sqos.partition().names(partitions);
    ReturnCode_t retcode = m_masterControlSubscriber->set_qos(sqos);
    if(retcode != ReturnCode_t::RETCODE_OK)
    {
        std::cout << "Error while changing partition qos on master control subscriber." << std::endl;
        return false;
    }
    return true;
}
```

**Comment by tobi4321** [comment] 2021-08-02 07:47
If i start the subscriber without the Partition MasterControl and after 20 samples i call enableSubscribingTopic(true), i get no output on the subscriber. When i change the order, that the MasterControl Partition is set on start and after 20 samples i call enableSubscribingTopic(false) i have the same problems.

**Comment by MiguelCompany** [comment] 2021-08-02 08:23
I think the responsible is `sqos.partition().set_max_size(5);`. This will set the maximum serialization size of the partitions to 5 bytes. I think the documentation is not clear enough, so we will update it soon.

Could you check removing the limit?
I would also add some debug output. Call `sqos.partition().names()` after setting them, just to make sure you have the expected partition list before calling `set_qos`.

**Comment by tobi4321** [comment] 2021-08-02 08:49
I removed the limits and outputed the contents of partition()names() for publisher, subscriber and the subscriber after 20 samples.

My output is:
`Starting LectorComParticipant
Initialization of LectorComParticipant started.
Initialization of MasterControlHandler started.
**Partitions of Publisher: MasterControl**
**Partitions of Subscriber: MasterControl**
(LectorComDataWriterListener) Publisher matched.
(LectorComDataReaderListener) Subscriber matched.
Initialization of MasterControlHandler finished succesfully.
Initialization of LectorComParticipant finished successfully.
Reader of Topic: MasterControlTopic | 0:202 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 1:169 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 2:159 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 3:158 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 4:163 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 5:158 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 6:148 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 7:166 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 8:165 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 9:154 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 10:157 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 11:154 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 12:157 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 13:164 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 14:168 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 15:159 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 16:156 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 17:165 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 18:159 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 19:164 Type: MasterControl PDO Value:This is a test string for json data.
Deactivate the Subscribing Topic
**Partitions of Subscriber after deactivating:**
Reader of Topic: MasterControlTopic | 20:178 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 21:161 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 22:163 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 23:164 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 24:162 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 25:162 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 26:162 Type: MasterControl PDO Value:This is a test string for json data.
Reader of Topic: MasterControlTopic | 27:157 Type: MasterControl PDO Value:This is a test string for json data.`

After the Subscriber partition list is empty, the incoming messages did not stop.

**Comment by EduPonz** [comment] 2021-08-02 12:11
Hi @tobi4321 ,

I have verified your report when changing the number of partitions of subscriber from some to none. I've submitted #2108 , which fixes the issue for me. Could you please verify? I'll include some regression tests in the upcoming days and the fix will be included in Fast DDS v2.4.0 by the end of September (an possibly included in other future patch releases).

I'll leave this ticket open until both you verify and the PR is merged. Thanks for your report and for iterating with us!

**Comment by tobi4321** [comment] 2021-08-04 12:26
Hi @EduPonz,
i have verified the bugfix. Now it works like expected.

**Comment by EduPonz** [comment] 2021-08-04 12:29
Hi @tobi4321 ,

That's great to hear! I'll leave the issue opened until de PR is merged

**Closed** 2021-08-06 07:18 UTC
Labels: bug
