### ISSUE TITLE
HelloExample docker and host cannot communicate

### ISSUE THREAD

**Issue by Heyangq** [eProsima/Fast-DDS#5265] opened 2024-09-26 10:29 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I use HelloExample to implement communication between the container and the host computer. I hope DDS works properly and supports shared memory

Subscribers can detect matches and unmatches, but no data is printed

### Current behavior

HelloExample docker and host cannot communicate
docker run 
--net host \
--ipc host \

### Steps to reproduce

In the docker: 
goToExamples
cd dds
cd HelloWorldExample
cd bin
./DDSHelloWorldExample publisher -s 1000

In the host:
./DDSHelloWorldExample subscriber

### Fast DDS version/commit

2.14.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by Mario-DL** [comment] 2024-09-26 12:25
Hi @Heyangq,

Thanks for using Fast DDS. The problem is that the subscriber is not able to open the shared memory segments because of the lack of permissions (created by a privileged user in the docker). You may overcome the situation by:
* Elevating subscriber's executable permissions (see `sudoers`).
* Avoid using SHM transport. More details in the [documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/shared_memory/shared_memory.html).
Seeing matches and unmatches its feasible because discovery traffic goes through network transport.

You may reach our support team at support@eProsima.com if you are interested in accelerating this feature. 
Feeling free to close this as it is a known current limitation.

**Closed by Mario-DL** 2024-09-26 12:25 UTC
Labels: triage
