### ISSUE TITLE
[15120] Misaligned msg when using nested struct

### ISSUE THREAD

**Issue by amdsobhy** [eProsima/Fast-DDS#2777] opened 2022-06-23 02:48 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Data published == data received by subscriber

### Current behavior

Data received by subscriber gets offset in memory by +4 bytes from what publisher is sending.

### Steps to reproduce

Using nested structs

a header struct of size 20bytes
a struct containing the header plus 6912028 bytes

It seems the issue goes away after adding a padding of 4 bytes inside the header so that the header is in multiples of 8 bytes. 

This shows that there is a bug either in the deserialization of data in this situation, where this 4bytes padding is inserted by the serializer to make the struct a multiple of 8 bytes and the deserializer fails to remove the padding which accounts for and the data structure to be misaligned when read by the user.

### Fast DDS version/commit

2.3.4

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Shared Memory Transport (SHM)

### Additional context

Ubuntu18.04 aarch64
Fast-dds-gen versions:  2.0.1 and master

**Comment by MiguelCompany** [comment] 2022-07-11 05:36
Hi @amdsobhy would you mind sharing an IDL reproducing this issue?

**Comment by amdsobhy** [comment] 2022-07-11 18:20
```
module DDS {

#define MAX_SIZE (1920 * 1200 * 3)

    struct Header
    {
        unsigned long long  eightbytes0;
        long                fourbytes1;
        long                fourbytes2;
        long                fourbytes3;
    };

    struct foo
    {
        Header data0;
        long fourbytes1;
        long fourbytes2;
        long fourbytes3;
        unsigned long fourbytes4;
        unsigned long fourbytes5;
        long fourbytes6;
        octet buffer[MAX_SIZE];
    };

};
```

**Comment by amdsobhy** [comment] 2022-08-11 18:53
@MiguelCompany I was hoping any insight on this issue, thank you.

**Comment by MiguelCompany** [comment] 2022-08-30 10:38
@amdsobhy Sorry for the late reply, some internal deliverables and then vacations got me away from this.

I think this is a bug in Fast DDS Gen. It should not consider foo as plain, as its CDR representation does not match the in-memory representation.

Could you check if the issue is fixed by changing the generated code so that the generated `is_plain` method returns `false` ?

**Comment by amdsobhy** [comment] 2022-09-02 03:36
Thank you @MiguelCompany, I will test it and let you know

**Comment by amdsobhy** [comment] 2022-09-13 21:37
Hi @MiguelCompany,

I tried changing the return of is_plain to false and that resulted into writer loan_sample() returning RETCODE_ILLEGAL_OPERATION

**Comment by MiguelCompany** [comment] 2022-09-15 05:28
@amdsobhy I have thought of another workaround. Just put `eightbytes0` at the end of `Header`. This way, the in-memory representation will match the CDR representation.

**Comment by amdsobhy** [comment] 2022-09-15 13:10
@MiguelCompany the offset is 4 bytes. I am already using an extra padding of 4 bytes in the heading as a workaround to this issue.

**Comment by Mario-DL** [comment] 2022-11-30 15:58
According to out [CONTRIBUTING.md](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md) guidelines, I am closing this issue due to inactivity.

**Closed by Mario-DL** 2022-11-30 15:58 UTC
Labels: need more info

**Comment by MiguelCompany** [comment] 2022-12-01 06:41
@amdsobhy This is not an issue in Fast DDS, but in Fast DDS Gen.

I created eProsima/Fast-DDS-Gen#141 to track it down.

**Comment by amdsobhy** [comment] 2022-12-02 20:54
Thank you @MiguelCompany
