### ISSUE TITLE
TypeObjectFactory, container types, and segmentation faults [13693]

### ISSUE THREAD

**Issue by fwr-ml** [eProsima/Fast-DDS#2184] opened 2021-09-05 09:11 UTC
<UPDATE>
Old title: "Missing check in TypeObjectFactory::get_[sequence|array|map]_identifier leads to segmentation fault"
This post just relates to that. I found more by now, but haven't traced all its details, yet. (next post)
<UPDATE/>

Greetings

## Expected Behavior
- recognize inner type as unknown
- return nullptr

## Current Behavior
In the function's body the type ID for the inner type gets retrieved, but the return value is _not_ checked for being a useful pointer. So even when it's not, the container type gets constructed and when calling add_type_identifier with it and further in the element_identifier (being a nullptr) gets checked for completeness, which leads to a segmentation fault.

## Steps to Reproduce
1. Call the function with a name, for which there is no type registered.

## System information
- Fast-RTPS version: tag v2.3.4
- OS: Linux fwr-ml 5.13.12-artix1-1

## Additional context
I modified fast-dds-gen and a copy of TypeObjectSource.stg to batch process the IDL files installed by ROS2 foxy to retrieve code, with which I build a type library, that contructs and registers TypeObjects on demand. (I couldn't find a way so far to enable type lookup service in ROS2. The lib's motivation is to enable applications to communicate with ROS2 nodes without the need to be ROS2 apps themselves or a need for a ROS2 installation in the system at runtime or knowing the types statically - just going by some config with type and member names to look for and someone dropping in a type lib with the current node-fleet's set of types.)

I'll need to modify the template to first make sure the inner type exists, anyway. But still adding the missing check here'd feel right.

Also, maybe related to ...? :
https://github.com/eProsima/Fast-DDS/issues/1243
https://github.com/eProsima/Fast-DDS/issues/1260

Regards

**Comment by fwr-ml** [comment] 2021-09-06 01:58
In the case of the type library I'm building, only complete TypeObjects get created - this cut the length of the .stg file to modify in half which made it slightly less scary, and the types aren't communicated over the wire (AFAIK), and I'm interested in the member's names.
This led me to recognize, that get_sequence_type_name gets called for a sequence member, which should have been known. (This function called get_sequence_identifier with bool complete = true and with false. The latter led to the seg fault as described above.)
There's more hair on the floor now than on my head, but at least I figured out that the sequence type (carrying complete types!) "isn't known", because it gets measured with is_type_identifier_complete and put into complete_identifiers_, but when looking for it, it gets measured like 'if (identifier->_d() == EK_COMPLETE)' while it never was assigned that value. (is_type_identifier_complete relays its question to the contained type, which in my problematic case says EK_COMPLETE).

So everywhere, where identifier->_d gets compared to EK_*, needs to be checked/validated/corrected.

**Comment by fwr-ml** [comment] 2021-09-06 16:12
I did those changes and for now it seems to work, though I do nothing more than pass the type lib a type name, it creates and registers it, and I check, if I can get a dynamic type after that.

```
@@ -1121,7 +1140,7 @@ const TypeIdentifier* TypeObjectFactory::get_stored_type_identifier(
     {
         return nullptr;
     }
-    if (identifier->_d() == EK_COMPLETE)
+    if ( is_type_identifier_complete(identifier) )
     {
         for (auto& it : complete_identifiers_)
         {
@@ -1157,12 +1176,13 @@ std::string TypeObjectFactory::get_type_name(
     {
         return "<NULLPTR>";
     }
-    if (identifier->_d() == EK_COMPLETE)
+    if ( is_type_identifier_complete(identifier) )
     {
         for (auto& it : complete_identifiers_)
         {
@@ -1289,7 +1323,7 @@ std::string TypeObjectFactory::generate_name_and_store_type_identifier(
 const TypeIdentifier* TypeObjectFactory::try_get_complete(
         const TypeIdentifier* identifier) const
 {
-    if (identifier->_d() == EK_COMPLETE)
+    if ( is_type_identifier_complete(identifier) )
     {
         return identifier;
     }
```

I'm not sure about it, but I assume there are no type objects for container types. So I didn't change anything in add_type_object nor in get_type_object.

**Comment by MiguelCompany** [comment] 2021-09-15 12:46
@fwr-ml You really found it! The key point here is that type ids are added to `complete_identifiers_` depending on `is_type_complete`, but are then looked up depending only on `EK_COMPLETE`, which will not be correct in all cases...

As you said, this is not true in the case of `complete_objects_`, where only `EK_COMPLETE` types are necessary.

Would you be so kind to prepare some regression tests on [here]() and creating a PR?

**Comment by fwr-ml** [comment] 2021-09-15 13:40
Sorry, but I've got my hands full. The diff excerpt in my earlier post is the cleanest I can offer right now. The TypeObjectFactory source in my working dir is riddled with test output and stuff.

**Comment by jparisu** [comment] 2021-09-17 06:08
@fwr-ml  thank you for this valuable information. We have been able to replicate the bug in the following PR https://github.com/eProsima/Fast-DDS/pull/2207 .
Sadly, it looks that the solution is not as simple as you proposed. I am working on that and I hope I find the error soon.

Please, feel free to keep commenting on this issue or contributing to the PR.

**Comment by fwr-ml** [comment] 2021-09-17 09:15
> Sadly, it looks that the solution is not as simple as you proposed.

I feared as much - I only gained partial insight of the class and only tested for successfully getting a DynamicType in my hands (not actually using it, yet). Now working on a wrapper for DynamicData to hide not needed complexity.
Thanks for taking over.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-02-14 09:20
I have opened a new issue explaining in detail the cause of the crash and its different manifestations in order to keep track in a single issue of the same bug.
I am closing this issue in favor of #3296.

**Closed by JLBuenoLopez-eProsima** 2023-02-14 09:20 UTC
Labels: bug, in progress
