### ISSUE TITLE
publisher-subcsriber communication completely stops in case of wifi driver reload

### ISSUE THREAD

**Issue by amitsingh21** [eProsima/Fast-DDS#3762] opened 2023-07-31 02:27 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Simple talker/listener setup running on same machine with udp transport and wifi interface explicitly whitleisted in fast_rtps_default_profile.xml. After reloading the wifi driver the communication stops altogether and never recovers unitl talker is restarted. Expceted behaviour is as soon as the wifi driver comes up and networking routes are up, communication should recover

### Current behavior

Currently communication stops altogether with below strace output, looks like we are not handling ENODEV error from sendmsg call and recreating the socket
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\360_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\357_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)

### Steps to reproduce

- start talker
   - docker run -d --name=talker --net=host -eFASTRTPS_DEFAULT_PROFILES_FILE=/tmp/fast_rtps_profile.xml -eROS_DOMAIN_ID=1 -v /tmp/fast_rtps_profile.xml:/tmp/fast_rtps_profile.xml osrf/ros:foxy-desktop bash -c 'sleep infinity'
   - source /opt/ros/foxy/setup.bash
   - ros2 run demo_nodes_cpp talker
- start listener 
   - docker run -d --name=listener --net=host -eFASTRTPS_DEFAULT_PROFILES_FILE=/tmp/fast_rtps_profile.xml -eROS_DOMAIN_ID=1 -v /tmp/fast_rtps_profile.xml:/tmp/fast_rtps_profile.xml osrf/ros:foxy-desktop bash -c 'sleep infinity'
   - source /opt/ros/foxy/setup.bash 
   - ros2 run demo_nodes_cpp listener
 - communication works fine
 - trigger driver reload simulating driver crashes in production
   - modprobe -r iwlwifi
   - modprobe  iwlwifi

### Fast DDS version/commit

v2.1.4

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### Additional context

looks like the interface index changes whenever the underlying wifi driver is being reloaded due to which the existing socket fds created by fastrtps are being returned with ENODEV since kernel dev layer is loaded with new ifindex but userspace code is still using the olderifindex before the driverreload. I think we should handle this ENODEV error and try to create a new socket until we succeed

### XML configuration file

```xml
?xml version="1.0" encoding="UTF-8" ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">

    <transport_descriptors>
        <transport_descriptor>
            <transport_id>udp_transport</transport_id>
            <type>UDPv4</type>
            <sendBufferSize>2097152</sendBufferSize>
            <receiveBufferSize>2097152</receiveBufferSize>
	    <maxMessageSize>1400</maxMessageSize>
            <maxInitialPeersRange>1024</maxInitialPeersRange>
            
            <interfaceWhiteList>
                <address>192.168.1.127</address>
            </interfaceWhiteList>
            
        </transport_descriptor>
    </transport_descriptors>
    <data_writer profile_name="writer_xml_conf_multicast_locators_profile" is_default_profile="true">
        <qos>
            <publishMode>
                <kind>ASYNCHRONOUS</kind>
            </publishMode>
        </qos>
        <historyMemoryPolicy>DYNAMIC</historyMemoryPolicy>
    </data_writer>
    
    <participant profile_name="UDPParticipant" is_default_profile="true">
	    <rtps>
             	
            <userTransports>
                <transport_id>udp_transport</transport_id>
            </userTransports>
            <sendSocketBufferSize>2097152</sendSocketBufferSize>
            <listenSocketBufferSize>2097152</listenSocketBufferSize>
            <useBuiltinTransports>false</useBuiltinTransports>
        </rtps>
    </participant>
</profiles>
```

### Network traffic capture

strace output indicating ENODEV received from kernel:
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\360_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\357_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\357_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\360_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\360_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\336_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\366_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)
[pid 20760] setsockopt(11, SOL_SOCKET, SO_SNDTIMEO_OLD, "\0\0\0\0\0\0\0\0\360_\327\35\24\0\0\0", 16) = -1 EDOM (Numerical argument out of domain)
[pid 20760] sendmsg(11, {msg_name={sa_family=AF_INET, sin_port=htons(7650), sin_addr=inet_addr("239.255.0.1")}, msg_namelen=16, msg_iov=[{iov_base="RTPS\2\3\1\17\1\17\237\204=\0\34\\\1\0\0\0\t\1\10\0\260\27\307d\"\312\4\373"..., iov_len=208}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = -1 ENODEV (No such device)

**Comment by JLBuenoLopez-eProsima** [comment] 2023-09-14 06:02
Thanks for your report @amitsingh21 

Regretfully, Fast DDS 2.1.x is no longer maintained (since May 2023) so I encourage you to upgrade to the latest release or at least to one of the maintained releases. You can find more info in the [release support document](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md).

Anyways, the behavior you are describing was the expected one in Fast DDS v2.1.x. Fast DDS used to initialize the communication interfaces only at the DomainParticipant creation. Thus, if the IP address changes, the expected behavior is for the DomainParticipant to stop communicating because the communication interface is another different one. Relaunching the DomainParticipant fixes the issue as you explain in your ticket.

Since Fast DDS v2.5.1, Fast DDS supports [dynamic network interfaces](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.html#dynamic-network-interfaces) so the user can force the DomainParticipant to re-scan the network interfaces and update them to reestablish communication without having to destroy and create the DomainParticipant again.

I am going to proceed and close the issue as the described behavior is the expected one for Fast DDS v2.1.x and also because Fast DDS v2.1.x is no longer maintained.

**Closed by JLBuenoLopez-eProsima** 2023-09-14 06:02 UTC
Labels: triage
