### ISSUE TITLE
Participant_A Received Paiticipant_B DROPPED_RTPSPARTICIPANT info when the Paiticipant_B's program is still running

### ISSUE THREAD

**Issue by LidarADAS** [eProsima/Fast-DDS#2163] opened 2021-08-24 07:14 UTC
I am using FastRTPS **v1.5** in my code to do service_discovery, for some reasons, it's hard for me to upgrade fastrtps to a new version.  I override the eprosima::fastrtps::ParticipantListener::onParticipantDiscovery function to recieve other participants' DiscoveryInfo. I have many participants in my system, each of them is in a separate process. Now I meet a problem, that Participant_A may received Participant_B **DROPPED_RTPSPARTICIPANT** info when the process of Participant_B is still running, and I'm sure that Participant_B has not been destructed. This situation is unstable, it may needs hours or days to reproduce. I wonder what will cause this problem. Thanks

**Comment by EduPonz** [comment] 2021-09-01 05:43
Hi @LidarADAS ,

What you are describing reads a lot like a [lease duration expiration](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html#lease-duration) event (the link is to the most up-to-date docs, but documents the concepts). Unfortunately, v1.5 does not have any support at this moment since it's rather old. What is blocking your from upgrading?

**Comment by LidarADAS** [comment] 2021-09-01 06:32
Thanks **@EduPonz** ,

I have read the docs you provided, the concepts also exist in **v1.5**, and I'm sure that I'v set it to the right value. 

From what I understand, participants in a same domain will send message periodically to each other. I am trying to debug FastRTPS source code, and found some participants do not send periodic message again in my failure scenario, so other participants receive **DROPPED_RTPSPARTICIPANT** info. I think it's the point, but I don't know **why a participant dose't send periodic message any more**.

My system has been working for a long time based on **FastRTPS v1.5**. The risk of upgrading to a new version is very high, and I found API of new version has been change a lot from v1.5.

**Comment by EduPonz** [comment] 2021-09-01 06:42
Hi @LidarADAS ,

Indeed a lot has changed and I understand the risks. How are you debugging? I might suggest capturing RTPS traffic using wireshark. After getting some captures, it is possible to filter them for participant announcements and try to see whether they are not sent at all, or they are simply sent a bit too late. What are your announcement period and lease duration settings?

**Comment by LidarADAS** [comment] 2021-09-01 07:05
Hi **@EduPonz** ,

The debugging method is **tracing the program's call stack, and printf some key info in the FastRTPS source code**.  I find the code snippet to send the periodic message, it's triggered by a timer, when the timer dose not been restarted, the problems arise. The code of the timer is very complex, so it's hard for me to debug deeply. 

Wireshark is a good debugging tool, but I don't think it's working to debug my problem, because I am sure the code to send the periodic message has not been called. 

My lease duration: 3s;
My announcement period: 12s;

**Comment by EduPonz** [comment] 2021-09-01 07:22
Hi @LidarADAS ,

I don't know if it's a typo, but the lease duration should always be smaller than the announcement period. We normally recommend the lease duration to be at least twice the announcement period, but thrice would be ideal. Something like:
* Lease duration: 12s
* Announcement period: 3s

>  I find the code snippet to send the periodic message, it's triggered by a timer, when the timer dose not been restarted, the problems arise

Can you please indicate where exactly is this happening?

**Comment by LidarADAS** [comment] 2021-09-01 07:44
Hi **@EduPonz** ,

Sorry for last wrong answer, in my system, the settings are the same with yours: 
- Lease duration: 12s
- Announcement period: 3s

In v1.5 source code, the timer is the file **ResendParticipantProxyDataPeriod.cpp**, and the code snippet is: 

`void ResendParticipantProxyDataPeriod::event(EventCode code, const char* msg)
{

    // Unused in release mode.
    (void)msg;

    if(code == EVENT_SUCCESS)
    {
        logInfo(RTPS_PDP,"ResendDiscoveryData Period");
        //FIXME: Change for liveliness protocol
        mp_PDP->getMutex()->lock();
        mp_PDP->getLocalParticipantProxyData()->m_manualLivelinessCount++;
        mp_PDP->getMutex()->unlock();
        mp_PDP->announceParticipantState(false);

        this->restart_timer();
    }
    else if(code == EVENT_ABORT)
    {
        logInfo(RTPS_PDP,"Response Data Period aborted");
    }
    else
    {
        logInfo(RTPS_PDP,"message: " <<msg);
    }
}`

When the situation is normal, the log print **ResendDiscoveryData Period** within 3s. When the problems arise, the **event** function dose not been called any more.

**Comment by EduPonz** [comment] 2021-09-02 08:38
Hi @LidarADAS ,

I've been doing some digging but I cannot find any place where the timer is cancel wrongly, nor can I reproduce the issue. It seems to me that you have encountered some kind of data race that causes the event to not being called anymore, but I have not find it. Unfortunately, there is not much more we can do with v1.5.0 at this point, as it is long EOL.

I understand your concerns with upgrading. Maybe you could consider upgrading to something like v1.8.4, which still has the same API that you are using, but there are a lot of improvements. One important detail though is that you would need to regenerate your data types and recompile the application, as the versions are not ABI compatible.

**Comment by LidarADAS** [comment] 2021-09-02 08:59
Hi **@EduPonz** ,

I am very glad to receive your reply again. As I mentioned before, it's hard for me to reproduce this issue in my system, so it may be more difficult for you. 

It sames too hard for me to solve this problem with fastrtps v1.5, so **we have made the decision to do upgrading**.  I will use the version:
- fastdds: v2.3.4
- fastcdr: v1.0.21
- foonathan_memory: v0.7

I'v glanced at the API of the fastdds new version, some API's namespace has been changed, and some API has been canceled. But I think I could finish the upgrading job with your help.

Looking forward to your reply again.

**Comment by EduPonz** [comment] 2021-09-02 09:55
Hi @LidarADAS ,

That's great to hear! We are always happy to see projects trusting us for their processes Your selected versions make total sense. By the end of the week, `foonathan_memory` is expected to release a new version that we will be using ourselves, so it probably makes sense to you as well (we have been doing tests on the latest commit without any problems).

Are you planning on using the new DDS specification compliant API, or will you stick to the one you are using already (we call it Fast RTPS API). The latter we'll be deprecated in the future, so I'd recommend using the DDS API instead, which is actively maintain and will not be deprecated since it's the one from the specification. We know from experience that migrating to the DDS API has some difficulties sometimes (it really depends on the application), but I think it's the best choice in the long run, since it's guaranteed that you'd never have to migrate again, and the API will not change.

We'll be happy to help along the road of course, just leave a comment or drop me an e-mail. I'll close this issue for now, but please feel free to re-open it or create a new one when needed.

**Comment by LidarADAS** [comment] 2021-09-02 10:37
Hi **@EduPonz** ,

There are last two questions please,

1. Where can I get the version of **foonathan_memory** you mentioned, and what's the version number of it?

2. What's the differences between **DDS specification compliant API** and **Fast RTPS API**?  I find some examples under "examples/C++/DDS", dose them all written with DDS API?

Thanks

**Comment by EduPonz** [comment] 2021-09-02 12:40
Hi @LidarADAS ,

> 1. Where can I get the version of **foonathan_memory** you mentioned, and what's the version number of it?

I'm sorry if I was not clear enough, what I meant is that `foonathan_memory` is getting a new release by the end of this week (see [this](https://github.com/eProsima/Fast-DDS/issues/2151#issuecomment-909398696). The tag we'll be pointing to the current head of the master branch, which we have tested successfully.

> 2\. What's the differences between **DDS specification compliant API** and **Fast RTPS API**?  I find some examples under "examples/C++/DDS", dose them all written with DDS API?

They are two different APIs for using the library. Fast RTPS API is the one we had before v2.0.0 (it's the one you were using in v1.5.0), whereas DDS API follows the DDS specification. We favor the DDS API over the Fast RTPS one, which means that new features are only added on the DDS API. Furthermore, issues arising on the library's higher layers are only addressed in the DDS API, as Fast RTPS in out of maintenance and will be deprecated at some point. All the documentation you can find [here](https://fast-dds.docs.eprosima.com/en/v2.3.4/) refers to the DDS API. Those examples to which you are referring are indeed written in using the DDS API.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-02-01 07:10
I am going to close this issue because it applies to an EOL version.

**Closed by JLBuenoLopez-eProsima** 2022-02-01 07:10 UTC
Labels: wontfix
