### ISSUE TITLE
Fastrps   client to fastrps server  TIME_WAIT  after disconnection and reconnection on client side [13649]

### ISSUE THREAD

**Issue by RamcharanPalnati** [eProsima/Fast-DDS#2013] opened 2021-06-17 09:08 UTC
Version : 1.9.1

In create participant from Fastrps client connection to fastrps server  ,unable to establish connection to fastrtps server due to TIME_WAIT  after disconnection and reconnection on client side using TCPV4 

## Expected Behavior
Able to establish connection from participant client to participant server after disconnection and reconnection using TCPV4 
## Current Behavior
unable to establish connection to fastrtps server due to TIME_WAIT  after disconnection and reconnection on client side using TCPV4 

## Steps to Reproduce

1.Create fasrtps TCP v4 participant  server
2.Create fasrtps TCPV4 participant client connecting to above participant server .
3.Disconnect and reconnect again from client to server
4.Unable to establish connection to server since the socket is in Time_wait from client to server .

## System information

- Fast-RTPS version: 1.9.3
- OS: Ubuntu 18.04
- Network interfaces: 
                      127.0.0.1
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by MiguelCompany** [comment] 2021-06-17 09:29
I think this may be somewhat related to #966

**Comment by RamcharanPalnati** [comment] 2021-06-17 10:27
I get TIME-WAIT instead of CLOSE_WAIT . Any body has idea on **wait_for_tcp_negotiation**  option in tcp transport descriptor

**Comment by RamcharanPalnati** [comment] 2021-06-23 04:45
@MiguelCompany Would upgrading to Fastdds 2.3.0 solve this issue ?

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 10:34
@RamcharanPalnati,

This issue might have been solved by #2470 which has been backported to [currently supported Fast DDS releases](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). I am going to close this issue as Fast DDS (formerly known as FastRTPS) 1.9.x is no longer supported. Feel free to reopen if the issue is still happening in newest versions of Fast DDS.

**Closed by JLBuenoLopez-eProsima** 2022-03-01 10:34 UTC
