### ISSUE TITLE
Compared to fastddsgenV2.30,fastddsgenV2.4.0 results in a significant decrease in throughput after just regenerating idls.

### ISSUE THREAD

**Issue by chunyisong** [eProsima/Fast-DDS#3438] opened 2023-04-06 02:25 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

FastddsgenV2.4.0(fastrpts2.10.0) should not decrease in throughput  compare to V2.3.0(fastrpts2.9.1) after just regenerating idls.Specific to my test,the  throughput should not less than 40000 samples per second ,which can not be worse than V2.30

### Current behavior

Just regenerating same idls and recompiling same sources ,fastddsgenV2.4.0 results in a significant 30% reduction in throughput compared to the fastddsgenV2.3.0. Specific to my repeated test out of total 10 times,the max throughput of V2.40 is 26000 (avg 25000 ) samples per second,compared to steady 40000 samples per second of V2.3.0.

### Steps to reproduce

`

// idl
struct DiscreteValue                           //12B
{
    unsigned short i; // info addr index       // 2B
    unsigned short q; // quality               // 2B
    long t; // time offset:t=realTime-baseTime // 4B
    unsigned long v; // value                  // 4B
};
struct AnalogValue                           //12B
{
    unsigned short i; // info addr index       // 2B
    unsigned short q; // quality               // 2B
    long t; // time offset:t=realTime-baseTime // 4B
    float v; // value                          // 4B
};
struct RuValuesMsg                             // 1316B
{
	@key
    unsigned long ruId;                  // 4B
    unsigned long long lastModifiedTime;    // 8B
    unsigned long long baseTime;            // 8B
                        //total values size <= 1296B =12*108
    // (analogValues+discreteValues).length <= 108
    AnalogValue analogValues[54];
    DiscreteValue discreteValues[54];
};

`
`

// Pseudocode to publish
auto interNs = chrono::duration_cast<chrono::nanoseconds>(chrono::duration<double>(1.0/40000));
auto begin = chrono::high_resolution_clock::now();
long loops = 0;
long totalSent = 0;
while(true){
    this_thread::sleep_until(begin+loops++ * interNs);
    if (ReturnCode_t::RETCODE_OK == writer_->loan_sample(loanSample))
            {
                    auto data = static_cast<RuValuesMsg*>(loanSample);
                    data->ruId(loops);
                    ok = writer_->write(loanSample);
                    if(ok){
                        totalSent++;
                    }
            }
}

`

### Fast DDS version/commit

fastrpts2.10.0 vs fastrpts2.9.1

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### XML configuration file

```xml
<data_writer profile_name="writer_profile" is_default_profile="true">
            <!-- <ignore_non_matching_locators>true</ignore_non_matching_locators> -->
            <historyMemoryPolicy>PREALLOCATED</historyMemoryPolicy>
            <topic>
                <historyQos>
                    <kind>KEEP_LAST</kind>
                    <depth>1</depth>
                </historyQos>
                <resourceLimitsQos>
                    <max_samples_per_instance>1</max_samples_per_instance>
                    <allocated_samples>100000</allocated_samples>
                    <max_instances>100000</max_instances>
                    <extra_samples>0</extra_samples>
                    <max_samples>0</max_samples>
                </resourceLimitsQos>
            </topic>
            <qos>
                <disable_heartbeat_piggyback>false</disable_heartbeat_piggyback>
                <data_sharing>
                    <!-- <kind>AUTOMATIC</kind> -->
                    <kind>OFF</kind>
                </data_sharing>
                <publishMode>
                    <kind>SYNCHRONOUS</kind>
                </publishMode>
                <lifespan>
                    <duration>
                        <sec>DURATION_INFINITY</sec>
                        <nanosec>0</nanosec>
                    </duration>
                </lifespan>
                <deadline>
                    <period>
                        <sec>DURATION_INFINITY</sec>
                        <nanosec>0</nanosec>
                    </period>
                </deadline>
                <durability>
                    <kind>VOLATILE</kind>
                    <!-- <kind>TRANSIENT_LOCAL</kind> -->
                </durability>
                <reliability>
                    <kind>BEST_EFFORT</kind>
                    <!-- <kind>RELIABLE</kind> -->
                    <max_blocking_time>
                        <sec>1</sec>
                        <nanosec>0</nanosec>
                    </max_blocking_time>
                </reliability>
                <disablePositiveAcks>
                    <enabled>true</enabled>
                    <duration>
                        <sec>1</sec>
                    </duration>
                </disablePositiveAcks>
                <liveliness>
                    <kind>AUTOMATIC</kind>
                    <lease_duration>
                        <sec>DURATION_INFINITY</sec>
                    </lease_duration>
                    <announcement_period>
                        <sec>60</sec>
                        <nanosec>0</nanosec>
                    </announcement_period>
                </liveliness>
            </qos>
            <times>
                <initialHeartbeatDelay>
                    <sec>0</sec>
                    <nanosec>50000000</nanosec>
                </initialHeartbeatDelay>
                <heartbeatPeriod>
                    <sec>5</sec>
                    <nanosec>0</nanosec>
                </heartbeatPeriod>
                <nackResponseDelay>
                    <sec>0</sec>
                    <nanosec>100000</nanosec>
                </nackResponseDelay>
                <nackSupressionDuration>
                    <sec>0</sec>
                    <nanosec>0</nanosec>
                </nackSupressionDuration>
            </times>
        </data_writer>
```

**Comment by jsantiago-eProsima** [comment] 2023-04-09 19:42
Hi @chunyisong, 

Does this performance decrease occur just by changing the Fast DDS-Gen version used to generate the types while keeping Fast DDS's version constant among tests?

**Comment by chunyisong** [comment] 2023-04-10 02:06
> Hi @chunyisong,
> 
> Does this performance decrease occur just by changing the Fast DDS-Gen version used to generate the types while keeping Fast DDS's version constant among tests?

Yes,this performance decrease occur just by Only changing the Fast DDS-Gen version to regenerate types while keeping FastDDS version/other source files/machine environments etc unchanged among tests.
I test this again with fastddsV2.9.1 vs fastddsV2.10.x(2.10.0 and 2.10.1,both seeming to no difference to me),the result as follows:

|fastdds Version |fastddsGen version|publisher samples per second|
|-|-|-|
|v2.9.1|v2.3.0|40000|
|v2.10.x|v2.3.0|40000|
|v2.10.x|v2.4.0|25000|

   @jsantiago-eProsima  Just from The result,fastddsGenV2.4.0 do something bad.

**Comment by jsantiago-eProsima** [comment] 2023-04-24 10:25
Hi @chunyisong,

Thanks for the info. Sadly, I tried reproducing this issue in clean Ubuntu (both Focal and Jammy) Docker images and got similar results when using types generated by Fast DDS-Gen 2.3.0 and 2.4.0. This is to be expected since the main change between types generated by these two versions is inside the `getMaxCdrSerializedSize` and `getKeyMaxCdrSerializedSize` functions that use a precalculated value on 2.4.0 whereas in 2.3.0 it has to calculate it every time it's needed (which should only happen once on type creation). You can see an example of these changes in the [PR that updated the types in Fast-DDS's repo](https://github.com/eProsima/Fast-DDS/pull/3316/files#diff-11cf3ac9e5bbd137b5e0f60e459aa22860a5ade544da69e2babbd76916300a24) 

My testing application is an example generated with Fast DDS-Gen with a modified sending loop to match the one from your pseudocode. I changed it to send messages until the DataReader leaves instead of stopping at 40000 but it is similar enough for the purpose of this test.

```
    int msgsent = 0;
    do
    {
        std::this_thread::sleep_until(st_time + (msgsent * std::chrono::microseconds(25)));
        if (ReturnCode_t::RETCODE_OK == writer_->loan_sample(sample))
        {
            auto data = static_cast<RuValuesMsg*>(sample);
            data->ruId(msgsent);
            auto ok = writer_->write(sample);
            if (ok)
            {
                msgsent++;
            }
        }
    } while (listener_.matched > 0);
```

In the table below you can see that my throughput and time spent between a sample and the next is pretty much the same with both versions. These tests were performed with Fast DDS's master branch.

| Fast DDS-Gen | Time | Samples | ns per sample |
|---|---|---|---|
| 2.3.0 | 1171234575 | 46830 | 25010 |
| 2.4.0 | 1150098131 | 45989 | 25008 |

Could you provide some more information regarding your setup?

**Comment by chunyisong** [comment] 2023-04-24 14:13
Hi @jsantiago-eProsima 
Thank you for reply. In fact ,the issue after re-compiling with new version comes from a monitoring project,which is too much complex.So I describe it in a simplified way,because I can not provide more information.What I find weird is that just recompile the project with new version to reproduce the issue.
I will try master branch until I am free. 
Close the issue anytime if it can not be reproduced.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-05-10 06:31
Closing the issue until it can be reproduced or it is reported by more users.

**Closed** 2023-06-01 02:48 UTC
Labels: need more info
