### ISSUE TITLE
Allow to ignore embedded thirdparty dependencies [12638]

### ISSUE THREAD

**Issue by alsora** [eProsima/Fast-DDS#2251] opened 2021-10-06 09:35 UTC
Fast-DDS contains a bunch of dependencies in the `thirdparty` directory.
Some of these (e.g. asio, fastcdr, etc) are git submodules and, unless the FORCE option is specified, can be provided by the system.
However, it looks like this is not the case for all the dependencies: boost, filewatch and nlohmann-json are always included (and built) from the `thirdparty` directory regardless of whether they could be provided by the system.

This can cause problems when cross-compiling fast-dds and when using package managers such as conan.

It would be good if there was a way to control all of these dependencies.

Note: I noticed this because of an error caused by different versions of boost present in my system.

**Comment by MiguelCompany** [comment] 2021-10-06 10:57
I think this is more related to what we export, instead of what we use. Seems to me it is similar to #1994, and it is possible that the fix proposed in #1998 would also apply here.

**Comment by MiguelCompany** [comment] 2022-01-03 11:19
@alsora PR #1998 has been merged and is part of release 2.5.0. Could you please check if this has been solved?

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 15:12
I am going to close this issue due to inactivity. A fix has been done and no feedback from the user has been received. @alsora, feel free to reopen if the issue is still happening.

**Closed by JLBuenoLopez-eProsima** 2022-03-01 15:12 UTC
