### ISSUE TITLE
Remote subscriber not responds when using FastDDS multicast [10617]

### ISSUE THREAD

**Issue by aram-father** [eProsima/Fast-DDS#1743] opened 2021-02-05 15:54 UTC
Hi, I'm an engineer looking into FastDDS for my future works.
I'd like to request your help for my current trouble.

I have 3 machines, namely **A**, **B**, and **C**.
**A** publishes 1mbytes size of topic, and both of **B** and **C** subscribe it.

Firstly, I've modified your [DDS Helloworld example](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExample) to publishes 1mbytes topic.
(Change memory management policy to `PREALLOCATED_WITH_REALLOC`)
I could see that the topic published from **A** is delivered well to **B** and **C**.

Secondly, I've added a little code snippet explained [here ](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/many_subscribers/many_subscribers.html?highlight=multicast)to publisher and subscriber.
In this case, subscribers do not respond(they respond to first 10~15 publications and halt).
I've already set below system parameters.
sysctl -w net.core.rmem_max = 16777216
sysctl -w net.core.wmem_max = 16777216
sysctl -w net.core.rmem_default = 16777216
sysctl -w net.core.wmem_default = 16777216

Could you please let me know how could I tackle this problem?

**Comment by MiguelCompany** [comment] 2021-02-18 14:21
First, I would like to have more information about your system. How is the connection between the 3 machines? Is it wireless, cabled? Are there many switches between them? Are the switches multicast aware?

Second, I see that our docs wrongly state that the multicast locators should be added to the DataWriter. That is not the case. In order for multicast to be used, it is enough to add the same multicast locator to every DataReader.

Adding the multicast locator to both will hinder performance, as the writer will receive (and then discard) the data it is sending, and the meta-traffic information from the readers to the writer may be lost.

One more thing I would like to know is the rate at which you are publishing and the QoS you are setting on both sides

**Comment by JLBuenoLopez-eProsima** [comment] 2022-01-26 10:29
I am going to proceed and close this issue as no answer providing the required information has been received. Also, being an issue related with an user application and not a bug in the library, we could not proceed further.

**Closed by JLBuenoLopez-eProsima** 2022-01-26 10:29 UTC
Labels: need more info
