### ISSUE TITLE
Get notified of new Data writers at application level?

### ISSUE THREAD

**Issue by mcelhennyi** [eProsima/Fast-DDS#2093] opened 2021-07-26 14:35 UTC
Hello,

I plan to use DDS as a way of transporting messages from one device to another. I have a gateway mechanism that only allows certain messages out of my system, to the other half of my system. 

I currently only tell my gateway what messages to let out, and would like the other side to be reactionary to the published messages - by setting up data readers on the fly. 

Is there a way to subscribe to notifications of new data writers such that I can on-the-fly setup data readers? I don't think, from what I have read, this type of paradigm is supported.

**Comment by EduPonz** [comment] 2021-07-26 14:40
Hi @mcelhennyi ,

This is indeed possible by the means of the `DomainParticipantListener` (see https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/disc_callbacks.html#domainparticipantlistener-discovery-callbacks). The only limitation is that entity creation are recommended to be performed outside the scope of the callbacks, that is whenever the application discovers a data writer, instead of creating the reader on the callback thread, it should take not of that and create the reader in a different thread (an application thread).

Hope that helps!

**Comment by mcelhennyi** [comment] 2021-07-26 14:43
> Hi @mcelhennyi ,
> 
> This is indeed possible by the means of the `DomainParticipantListener` (see https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/disc_callbacks.html#domainparticipantlistener-discovery-callbacks). The only limitation is that entity creation are recommended to be performed outside the scope of the callbacks, that is whenever the application discovers a data writer, instead of creating the reader on the callback thread, it should take not of that and create the reader in a different thread (an application thread).
> 
> Hope that helps!

Very nice, I think this is exactly what I needed. Thanks!

**Comment by EduPonz** [comment] 2021-07-26 14:44
I'm glad to hear that! I'll go ahead and close the issue for now, please feel free to re-open is anything surfaces

**Closed by EduPonz** 2021-07-26 14:44 UTC

**Comment by mcelhennyi** [comment] 2021-07-29 18:56
@EduPonz How do I filter off my participant/publisher when this call back is hit? It seems my own participant/publisher is triggering this on it self.

**Comment by mcelhennyi** [comment] 2021-07-29 19:25
Another question:
Is it possible to get this on_publisher_discovery call back when the reader is late aka is turned on AFTER the writer is created?

I have this working only when I turn on my reader side then turn on the writer side.

Is there some functionality that I can enable that allows the writer to notify new participants on the network of itself?

**Comment by EduPonz** [comment] 2021-07-30 06:26
Hi @mcelhennyi ,

> How do I filter off my participant/publisher when this call back is hit? It seems my own participant/publisher is triggering this on it self.

You are indeed correct. Currently, there is no configuration parameter to avoid this. What you could do is to filter it out yourself in the callback implementation. The Prefix part of the GUID is a unique identifier for the participant, so you can use it for your condition:
```
if (participant->guid().guidPrefix == info.info.guid().guidPrefix)
{
    std::cout << "Discovered data writer comes from this participant" << std::endl;
}
```

> Is it possible to get this on_publisher_discovery call back when the reader is late aka is turned on AFTER the writer is created?
> 
> I have this working only when I turn on my reader side then turn on the writer side.

I just tried this and it works for me in both orders as expected. Can you provide some way to reproduce?

> Is there some functionality that I can enable that allows the writer to notify new participants on the network of itself?

Indeed. You can achieve this with `on_participant_discovery()` callback (see https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/disc_callbacks.html). Two remarks here:
1. The callback is not triggered for the participant itself
2. You will only discover participants in your domain

I hope that helps!
