### ISSUE TITLE
Docker container-Host communication fails after restart (TCP) (FastDDS Bug with docker env confirmed) [13677]

### ISSUE THREAD

**Issue by ilikecola** [eProsima/Fast-DDS#2134] opened 2021-08-09 16:38 UTC
## Expected Behavior
Docker container-Host communication works will after docker container restart. Docker container act TCP Client and subscriber, Host act TCP Sever and publisher.

## Current Behavior
Docker container-Host communication fails after restart, Docker container ESTABLISHED TCP connection to Host(TCP Server) , but DW/DR are not matched, however first time everything works well.

## Steps to Reproduce
1.Start Docker container with Helloworld act as TCP Client
2.Start host Helloworld acting as TCP Server
3.Communication working well
4.Restart Docker container by "docker-compose restart"
5.Host Helloworld cannot match Docker container again

## System information
Docker version 20.10.7, build f0df350
base Ubuntu:20.04

- Fast-RTPS version: 2.2.0
- OS:Ubuntu:20.04
- Network interfaces:  docker0:172.17.0.1 using docker host drvier

## Solution tried 
1.Helloworld is working perfectly on both Host(TCP) -- Code is good.
2.Helloworld is working perfectly inside containter manully(not using CMD or Entrypoint) -- docker network seems good
3.Wireshark shows many DUP ACK.
4.Randomly after restart, communication is working but failed after restart again.
5.According participant listener, participant can be discovered after container restart but DW or DR cann not discovered. 

## Dockerfile
```
FROM amd64/ubuntu:20.04 as build
COPY --chown=root:root ./entrypoint.sh /usr/local/bin/
COPY --chown=root:root ./fastddslib/ /usr/local/lib/
COPY ./coverage_basic /usr/local/bin/coverage_basic
COPY ./DEFAULT_FASTRTPS_PROFILES.xml /usr/local/bin/
RUN ln -s /usr/local/lib/libtinyxml2.so.3.0.0 /usr/local/lib/libtinyxml2.so.3 \
    && ln -s /usr/local/lib/libfastcdr.so.1.0.15 /usr/local/lib/libfastcdr.so.1 \
    && ln -s /usr/local/lib/libfastrtps.so.2.2.0  /usr/local/lib/libfastrtps.so.2 \
    && ln -s /usr/local/lib/libtinyxml2.so.3 /usr/local/lib/libtinyxml2.so \
    && ln -s /usr/local/lib/libfastcdr.so.1 /usr/local/lib/libfastcdr.so \
    && ln -s /usr/local/lib/libfastrtps.so.2  /usr/local/lib/libfastrtps.so \
    && ln -s /usr/local/lib/libcrypto.so.1.1 /usr/local/lib/libcrypto.so \
    && ln -s /usr/local/lib/libssl.so.1.1 /usr/local/lib/libssl.so \
    && echo 'export LD_LIBRARY_PATH=/usr/local/lib/' >> ~/.bashrc
ENV LD_LIBRARY_PATH="/usr/local/lib/"
WORKDIR /usr/local/bin/
CMD ["coverage_basic","publisher"]
```
## DockerCompose
```
version: '3'
services:
    fastdds_demo:
        build:
                context: ./
                dockerfile: Dockerfile
        container_name: fastdds_demo
        network_mode: host
        stdin_open: true
        tty: true
        volumes:
                - ./DEFAULT_FASTRTPS_PROFILES.xml:/usr/local/bin/DEFAULT_FASTRTPS_PROFILES.xml
```

**Comment by rh-08** [comment] 2021-08-10 10:06
I also encountered this problem，

How to solve it?

Thanks a lot!

**Comment by ilikecola** [comment] 2021-08-15 15:10
After digging fastdds code, the most possible reason is that docker-restart will not triger remote host to create a new writer proxy for reader.
https://github.com/eProsima/Fast-DDS/blob/6b55651b6edfaf0a201fce26e1861ceef84696a4/src/cpp/rtps/reader/StatefulReader.cpp#L180
matched_writers_pool_ will not empty, but writer(after docker restart) is not matched actually.

Maybe it's related to guid or something else.

**Comment by amfern** [comment] 2021-11-10 06:55
Can you post, how you run the docker?

**Comment by amfern** [comment] 2021-11-10 21:16
can you try mounting `/dev/shm` into the container `pid: "host"`

**Comment by ilikecola** [comment] 2021-11-12 17:50
Update both compose file with following:
```
volumes:
                - ./DEFAULT_FASTRTPS_PROFILES.xml:/usr/local/bin/DEFAULT_FASTRTPS_PROFILES.xml
                - /dev/shm:/dev/shm
```

However, TCP server restart is working now, but TCP client restart is still stuck.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 14:26
Sorry, @ilikecola,

Fast DDS 2.2.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). I suggest using another Fast DDS release and checking if your issue has been solved. Recently #2470 was merged and backported to the officially supported releases. The changes introduced may fixed the issue you have. Feel free to reopen the issue if after testing with a supported release the issue is still happening.

**Closed by JLBuenoLopez-eProsima** 2022-03-01 14:26 UTC
