### ISSUE TITLE
2.4.0 can't build under Ubuntu/Linaro 5.4.0(aarch64) [12545]

### ISSUE THREAD

**Issue by chenzhengxi** [eProsima/Fast-DDS#2219] opened 2021-09-22 12:11 UTC
2.4.0 can't build under Ubuntu/Linaro 5.4.0(aarch64)
but 2.3.4 is OK
/home/chenzhengxi/repo/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp:27:87:   required from here
/usr/aarch64-linux-gnu/include/c++/5/ext/new_allocator.h:120:4: error: use of deleted function ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<eprosima::fastdds::rtps::FlowController>]’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^
In file included from /usr/aarch64-linux-gnu/include/c++/5/bits/stl_algobase.h:64:0,
                 from /usr/aarch64-linux-gnu/include/c++/5/bits/char_traits.h:39,
                 from /usr/aarch64-linux-gnu/include/c++/5/ios:40,
                 from /usr/aarch64-linux-gnu/include/c++/5/ostream:38,
                 from /usr/aarch64-linux-gnu/include/c++/5/iostream:39,
                 from /home/chenzhengxi/repo/Fast-DDS/include/fastdds/rtps/common/Time_t.h:24,
                 from /home/chenzhengxi/repo/Fast-DDS/include/fastdds/rtps/attributes/WriterAttributes.h:22,
                 from /home/chenzhengxi/repo/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.hpp:5,
                 from /home/chenzhengxi/repo/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp:1:
/usr/aarch64-linux-gnu/include/c++/5/bits/stl_pair.h:127:17: note: ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = std::unique_ptr<eprosima::fastdds::rtps::FlowController>]’ is implicitly deleted because the default definition would be ill-formed:
       constexpr pair(const pair&) = default;
                 ^
/usr/aarch64-linux-gnu/include/c++/5/bits/stl_pair.h:127:17: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = eprosima::fastdds::rtps::FlowController; _Dp = std::default_delete<eprosima::fastdds::rtps::FlowController>]’
In file included from /usr/aarch64-linux-gnu/include/c++/5/bits/locale_conv.h:41:0,
                 from /usr/aarch64-linux-gnu/include/c++/5/locale:43,
                 from /usr/aarch64-linux-gnu/include/c++/5/iomanip:43,
                 from /home/chenzhengxi/repo/Fast-DDS/include/fastdds/rtps/common/GuidPrefix_t.hpp:28,
                 from /home/chenzhengxi/repo/Fast-DDS/include/fastdds/rtps/common/Guid.h:24,
                 from /home/chenzhengxi/repo/Fast-DDS/include/fastdds/rtps/attributes/WriterAttributes.h:23,
                 from /home/chenzhengxi/repo/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.hpp:5,
                 from /home/chenzhengxi/repo/Fast-DDS/src/cpp/rtps/flowcontrol/FlowControllerFactory.cpp:1:

**Comment by MiguelCompany** [comment] 2021-09-22 12:34
@chenzhengxi This is a duplicate of #2174, and should be fixed by #2220. Kindly check on your side.

**Closed** 2021-09-22 13:50 UTC
