### ISSUE TITLE
There will be a link error that "undefined reference to `std::__future_base...." when cross compiling with openssl 1.0.2 [8993]

### ISSUE THREAD

**Issue by NoName-Do** [eProsima/Fast-DDS#1082] opened 2020-03-21 12:07 UTC
## Expected Behavior

Pass cross compilation.
## Current Behavior

**There will be link error as below.**
_[  1%] Linking CXX shared library libfastrtps.so
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `eprosima::fastrtps::rtps::TCPChannelResourceSecure::read(unsigned char*, unsigned int, std::error_code&)':
TCPChannelResourceSecure.cpp:(.text+0x1560): undefined reference to 
................_
## Steps to Reproduce

**1. Cross compiling tinyxml, fast-cdr, foonathan-memory.
2. Cross compiling  openssl 1.0.2 with below configure.
 a)./Configure linux-armv4 --cross-compile-prefix=arm-linux-gnueabi- -d shared --prefix=[MY INSTALL FOLDER]
 b) Add "-march=armv7-a" compilation flag to generated Makefile
3. Cross compiling Fast-RTPS.**

## System information

[  1%] Linking CXX shared library libfastrtps.so
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `eprosima::fastrtps::rtps::TCPChannelResourceSecure::read(unsigned char*, unsigned int, std::error_code&)':
TCPChannelResourceSecure.cpp:(.text+0x1560): undefined reference to `std::__future_base::_Result_base::_Result_base()'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `eprosima::fastrtps::rtps::TCPChannelResourceSecure::send(unsigned char const*, unsigned int, unsigned char const*, unsigned int, std::error_code&)':
TCPChannelResourceSecure.cpp:(.text+0x2160): undefined reference to `std::__future_base::_Result_base::_Result_base()'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `std::__future_base::_Result<unsigned int>::~_Result()':
TCPChannelResourceSecure.cpp:(.text._ZNSt13__future_base7_ResultIjED2Ev[_ZNSt13__future_base7_ResultIjED5Ev]+0x20): undefined reference to `std::__future_base::_Result_base::~_Result_base()'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `std::__future_base::_Result<unsigned int>::~_Result()':
TCPChannelResourceSecure.cpp:(.text._ZNSt13__future_base7_ResultIjED0Ev[_ZNSt13__future_base7_ResultIjED5Ev]+0x20): undefined reference to `std::__future_base::_Result_base::~_Result_base()'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `std::__future_base::_Result<unsigned int>::_M_destroy()':
TCPChannelResourceSecure.cpp:(.text._ZNSt13__futur**e_base7_ResultIjE10_M_destroyEv[_ZNSt13__future_base7_ResultIjE10_M_destroyEv]+0x40): undefined reference to `std::__future_base::_Result_base::~_Result_base()'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `std::promise<unsigned int>::set_value(unsigned int const&)':
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjE9set_valueERKj[_ZNSt7promiseIjE9set_valueERKj]+0x158): undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `std::promise<unsigned int>::set_value(unsigned int&&)':
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjE9set_valueEOj[_ZNSt7promiseIjE9set_valueEOj]+0x158): undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `std::future<unsigned int>::get()':
TCPChannelResourceSecure.cpp:(.text._ZNSt6futureIjE3getEv[_ZNSt6futureIjE3getEv]+0x9c): undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long long, std::ratio<1ll, 1ll> >, std::chrono::duration<long long, std::ratio<1ll, 1000000000ll> >)'
TCPChannelResourceSecure.cpp:(.text._ZNSt6futureIjE3getEv[_ZNSt6futureIjE3getEv]+0xdc): undefined reference to `std::__exception_ptr::operator==(std::__exception_ptr::exception_ptr const&, std::__exception_ptr::exception_ptr const&)'
TCPChannelResourceSecure.cpp:(.text._ZNSt6futureIjE3getEv[_ZNSt6futureIjE3getEv]+0xe8): undefined reference to `std::__exception_ptr::exception_ptr::~exception_ptr()'
TCPChannelResourceSecure.cpp:(.text._ZNSt6futureIjE3getEv[_ZNSt6futureIjE3getEv]+0x160): undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(std::__exception_ptr::exception_ptr const&)'
TCPChannelResourceSecure.cpp:(.text._ZNSt6futureIjE3getEv[_ZNSt6futureIjE3getEv]+0x168): undefined reference to `std::rethrow_exception(std::__exception_ptr::exception_ptr)'
TCPChannelResourceSecure.cpp:(.text._ZNSt6futureIjE3getEv[_ZNSt6futureIjE3getEv]+0x170): undefined reference to `std::__exception_ptr::exception_ptr::~exception_ptr()'
CMakeFiles/fastrtps.dir/transport/TCPChannelResourceSecure.cpp.o: In function `std::promise<unsigned int>::~promise()':
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjED2Ev[_ZNSt7promiseIjED5Ev]+0x154): undefined reference to `std::current_exception()'
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjED2Ev[_ZNSt7promiseIjED5Ev]+0x174): undefined reference to `std::__exception_ptr::exception_ptr::swap(std::__exception_ptr::exception_ptr&)'
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjED2Ev[_ZNSt7promiseIjED5Ev]+0x17c): undefined reference to `std::__exception_ptr::exception_ptr::~exception_ptr()'
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjED2Ev[_ZNSt7promiseIjED5Ev]+0x184): undefined reference to `std::__exception_ptr::exception_ptr::~exception_ptr()'
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjED2Ev[_ZNSt7promiseIjED5Ev]+0x1bc): undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)'
TCPChannelResourceSecure.cpp:(.text._ZNSt7promiseIjED2Ev[_ZNSt7promiseIjED5Ev]+0x224): undefined reference to `std::__future_base::_Result_base::~_Result_base()'
- Fast-RTPS version: 1.9.4 and git master repo
- OS:Ubuntu 16.04
- Network interfaces: N/A 
                      
- ROS2: N/A
        

## Additional context

**1. Let Openssl missing during generating CMakeCache(do not use openssl), cross compiling procedure can be pass. Cmake output as below:** 
_-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_kill_

**2. Compiling Fast-RTPS , using system g++ and with Openssl 1.0.2, can be pass.**

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 09:55
Sorry @NoName-Do,

Fast DDS (formerly known as FastRTPS) 1.9.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). I am going to close this issue. Feel free to reopen if the issue is still present in some of the supported versions of Fast DDS.

**Closed by JLBuenoLopez-eProsima** 2022-03-01 09:55 UTC
