### ISSUE TITLE
Error generating ROS2 idl messages

### ISSUE THREAD

**Issue by Andrea2202** [eProsima/Fast-DDS#1789] opened 2021-02-25 14:53 UTC
Hello everybody,
I am trying to generate structures to communicate using ros2 idl messages.
I'm able to run fastddgen for all packages except for ros2 navigation ones

The error that appears for the nav_msgs / msg / OccupancyGrid.idl message is

    builtin_interfaces :: msg :: Time is already defined

I enclose the structure here

// generated from rosidl_adapter / resource / msg.idl.em
// with input from nav_msgs / msg / OccupancyGrid.msg
// generated code does not contain a copyright notice

#include "nav_msgs / msg / MapMetaData.idl"
#include "std_msgs / msg / Header.idl"

module nav_msgs {
  module msg {
    @verbatim (language = "comment", text =
      "This represents a 2-D grid map, in which each cell represents the probability of occupancy.")
    struct OccupancyGrid {
      std_msgs :: msg :: Header header;

      @verbatim (language = "comment", text =
        "MetaData for the map")
      nav_msgs :: msg :: MapMetaData info;

      @verbatim (language = "comment", text =
        "The map data, in row-major order, starting with (0,0). Occupancy" "\ n"
        "probabilities are in the range [0,100]. Unknown is -1.")
      sequence <int8> data;
    };
  };
};

You can also tell me why, for some messages are only generated the structure
Generating Type definition files ...
Generating TypeObject files ...
And not even pubsub files?

Thanks in advance

#https://github.com/eProsima/Fast-DDS-Gen/issues/52

## Steps to Reproduce

1.
2.
3.
4.

## System information

- Fast-RTPS version: 
- OS: 
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by MiguelCompany** [comment] 2021-02-26 06:02
I'm closing this, since it is a duplicate of eProsima/Fast-DDS-Gen#52.

**Closed by MiguelCompany** 2021-02-26 06:02 UTC
