### ISSUE TITLE
Multi-transport is not support?

### ISSUE THREAD

**Issue by denverfu** [eProsima/Fast-DDS#4049] opened 2023-11-24 10:50 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

If I add 2 user defined transports to DomainParticipantQos, I can publish 1 change on the 2 transport layer in parallel.

### Current behavior

If I add shm and udp4 to user defined transports of DomainParticipantQos, I only can receive udp data in subscriber but shm.

### Steps to reproduce

1、Modify file:/Fast-DDS/Fast-DDS/examples/cpp/dds/AdvancedConfigurationExample/AdvancedConfigurationPublisher.cpp, 
From:
                case UDPv4:
                {
                    auto udp_transport = std::make_shared<UDPv4TransportDescriptor>();
                    pqos.transport().user_transports.push_back(udp_transport);
                }
To
                case UDPv4:
                {
                    auto udp_transport = std::make_shared<UDPv4TransportDescriptor>();
                    pqos.transport().user_transports.push_back(udp_transport);
                    auto shm_transport = std::make_shared<SharedMemTransportDescriptor>();
                    pqos.transport().user_transports.push_back(shm_transport);
                }
2、build
cd /Fast-DDS/Fast-DDS/examples/cpp/dds/AdvancedConfigurationExample/
mkdir build
cmake .. && cmake --build .

3、Test in  /Fast-DDS/Fast-DDS/examples/cpp/dds/AdvancedConfigurationExample/build
Terminal1:
./AdvancedConfigurationExample subscriber --transport shm
Terminal2:
./AdvancedConfigurationExample subscriber --transport udp
Terminal3:
./AdvancedConfigurationExample publisher --transport udp

4、Result
Terminal1:
⇒  ./AdvancedConfigurationExample subscriber --transport shm
Subscriber Participant created with DataReader Guid [ 01.0f.a3.73.a0.1b.95.8e.00.00.00.00|0.0.1.4 ].
Subscriber running. Please press CTRL+C to stop the Subscriber.

Terminal2:
⇒  ./AdvancedConfigurationExample subscriber --transport udp
Subscriber Participant created with DataReader Guid [ 01.0f.a3.73.9c.1c.76.6a.00.00.00.00|0.0.1.4 ].
Subscriber running. Please press CTRL+C to stop the Subscriber.
Subscriber matched [ 01.0f.a3.73.c5.1c.b3.8b.00.00.00.00|0.0.1.3 ].
Message HelloWorld  2 RECEIVED
Message HelloWorld  3 RECEIVED
Message HelloWorld  4 RECEIVED
Message HelloWorld  5 RECEIVED
Message HelloWorld  6 RECEIVED

Terminal3:
⇒  ./AdvancedConfigurationExample publisher 
Publisher Participant created with DataWriter Guid [ 01.0f.a3.73.01.1d.71.9a.00.00.00.00|0.0.1.3 ].
Publisher running. Please press CTRL+C to stop the Publisher at any time.
Message: HelloWorld  with index: 1 SENT
Publisher matched [ 01.0f.a3.73.9c.1c.76.6a.00.00.00.00|0.0.1.4 ].
Message: HelloWorld  with index: 2 SENT
Message: HelloWorld  with index: 3 SENT
Message: HelloWorld  with index: 4 SENT
Message: HelloWorld  with index: 5 SENT
Message: HelloWorld  with index: 6 SENT

### Fast DDS version/commit

Version 2.12

git checkout origin/2.12.0

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4, Data-sharing delivery

### Additional context

openEuler-22.03-LTS-SP1-x86_64

### XML configuration file

```xml
none
```

### Relevant log output

```shell
none
```

### Network traffic capture

none

**Comment by EduPonz** [comment] 2023-11-24 10:58
Hi @denverfu,

I'm afraid that what you are seeing is the expected behaviour, but not because of the reasons you are inferring. As you can see [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/shared_memory/shared_memory.html#enabling-shared-memory-transport), as soon a DomainParticipant has a UDP transport enabled, SHM is not used for discovery. In your case, this means that the subscriber which only has a SHM transport cannot discovery the publisher (and vice-versa) and hence it's unable to receive data from it.

![image](https://github.com/eProsima/Fast-DDS/assets/7962388/7a7e1875-3738-4784-af1a-8d21c243eb4d)

I'm going to go ahead and close this issue for now. Please feel free to re-open it should you find it convenient.

**Closed by EduPonz** 2023-11-24 10:58 UTC
Labels: invalid
