### ISSUE TITLE
Participant announcements keep being posted with the initial interval [13666]

### ISSUE THREAD

**Issue by VladimirVassiliev** [eProsima/Fast-DDS#2069] opened 2021-07-15 06:24 UTC
Sometimes, participant announcements keep being sent with the interval specified in the `initial_announcements.period` forever (almost).
## Expected Behavior

Only the the number of participant announcements specified by the `initial_announcements.count` parameter should be sent with the initial interval
## Current Behavior

Sometimes, participant announcements keep being sent with the interval specified in the `initial_announcements.period` forever (almost).
## Steps to Reproduce
I don't have a simple example to reproduce this problem.

## System information

- Fast-RTPS version: 2.01
- OS: 
- Network interfaces: 
                      
- ROS2: 
        

## Additional context
The reason seems to be a race condition in the `PDP::set_next_announcement_interval()` function that decrements the counter. That function is called from the thread calling the `PDP::initPDP()` and from the timer thread:
```
    resend_participant_info_event_ = new TimedEvent(mp_RTPSParticipant->getEventResource(),
                    [&]() -> bool
                    {
                        announceParticipantState(false);
                        set_next_announcement_interval();
                        return true;
                    },
                    0);
```

A workaround is to set the `initial_announcement.counter` to 0 and/or set the `initial_announcement.period` to the same value as `leaseDuration`.
## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 14:05
Sorry @VladimirVassiliev,

Fast DDS 2.0.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). Also, efforts to fix several issues reported by ThreadSanitizer are being made. So I am going to close this issue as the related version is no longer supported and the issue is expected to be fixed soon in the newer versions.

**Closed by JLBuenoLopez-eProsima** 2022-03-01 14:06 UTC
