### ISSUE TITLE
idl data type convert

### ISSUE THREAD

**Issue by Xuezha-Guo** [eProsima/Fast-DDS#2667] opened 2022-05-07 08:12 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I try to create a data type with IDL
IDL code:
```
struct AME_DDS
{
    map<string, string> status;
};
```
shell code:
```
fastddsgen -python AME_DDS.idl 
export LD_LIBRARY_PATH=~/Fast-DDS-python/install/lib
echo 'export LD_LIBRARY_PATH=~/Fast-DDS-python/install/lib' >> ~/.bashrc
cmake . -DCMAKE_PREFIX_PATH=~/Fast-DDS/install（/lib）
make
```
it's supposed to be ok cause document said that Fast DDS-Gen supports maps and only Primitive types are supported. String is one of the Primitive types.
Other common data types are running normally.

### Current behavior

when i do 'make' command , there is error:
```
[ 66%] Swig compile AME_DDS.i for python
/home/gch/Fast-DDS/install/include/fastdds/dds/core/LoanableTypedCollection.hpp:68: Warning 389: operator[] ignored (consider using %extend)
/home/gch/Fast-DDS/install/include/fastdds/dds/core/LoanableTypedCollection.hpp:93: Warning 389: operator[] ignored (consider using %extend)
/home/gch/gch/web_project/AME_DDS/AME_DDS.i:83: Error: Syntax error in input(1).
CMakeFiles/AME_DDSWrapper_swig_compilation.dir/build.make:73: recipe for target 'CMakeFiles/AME_DDSWrapper.dir/AME_DDSPYTHON.stamp' failed
make[2]: *** [CMakeFiles/AME_DDSWrapper.dir/AME_DDSPYTHON.stamp] Error 1
make[2]: *** 正在删除文件“CMakeFiles/AME_DDSWrapper.dir/AME_DDSPYTHON.stamp”
CMakeFiles/Makefile2:139: recipe for target 'CMakeFiles/AME_DDSWrapper_swig_compilation.dir/all' failed
make[1]: *** [CMakeFiles/AME_DDSWrapper_swig_compilation.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
```

### Steps to reproduce

mentioned above

### Fast DDS version/commit

linux installation from sources

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

TCPv4

### Additional context

Ubuntu 18.04.6 LTS
PyCharm

**Comment by EduPonz** [comment] 2022-05-09 05:06
Closing this as duplicate of eProsima/Fast-DDS-python#26

**Closed by EduPonz** 2022-05-09 05:06 UTC
Labels: triage
