### ISSUE TITLE
Unable to write from  publisher to subscriber processing  at higher frequencies like 25 ms, having multiple pubs and subs in the participant

### ISSUE THREAD

**Issue by ramcharan-palnati** [eProsima/Fast-DDS#2899] opened 2022-08-02 10:48 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The Publisher should send message to subscriber processing at higher frequencies like 25 ms, having multiple pubs and subs in the participant in a multi-threaded environment. It can send message at frequency 250 ms for the same configuration.

### Current behavior

The Publisher dont send messages to subscriber processing at higher frequencies like 25 ms, having multiple pubs and subs in the participant in a multi-threaded environment. It can send message at a frequency of 250 ms for the same configuration.

### Steps to reproduce

Create two participants having multiple publishers and subscribers. Send a message from every publisher at a higher frequency like 25ms. Check at every subscriber whether they receive messages sent from the publisher or not.
I have checked for the packet loss but I dont see them at network interface level and wireshark .
I have used the below configuration for publisher and subscribers : 

PUBLISHER:

                   `pubParam.topic.topicKind = eprosima::fastrtps::rtps::NO_KEY;
                    pubParam.topic.historyQos.kind = eprosima::fastrtps::KEEP_LAST_HISTORY_QOS;
                    pubParam.topic.historyQos.depth = 2048;
                    pubParam.topic.resourceLimitsQos.max_samples = 2048;
                    pubParam.topic.resourceLimitsQos.allocated_samples = 2048;
                    pubParam.times.heartbeatPeriod.seconds = 0;
                    pubParam.times.heartbeatPeriod.nanosec = 1000*1000;
                    pubParam.qos.m_reliability.kind = eprosima::fastrtps::RELIABLE_RELIABILITY_QOS;
                    pubParam.qos.m_publishMode.kind = eprosima::fastrtps::ASYNCHRONOUS_PUBLISH_MODE;                    
                    pubParam.qos.m_durability.kind = eprosima::fastrtps::VOLATILE_DURABILITY_QOS;
                   `
SUBSCRIBER: 

                   `subParam.topic.topicKind = eprosima::fastrtps::rtps::NO_KEY;
                    subParam.topic.topicDataType = topicDataType;
                    subParam.topic.topicName = topicName;
                    subParam.topic.historyQos.kind = eprosima::fastrtps::KEEP_LAST_HISTORY_QOS;
                    subParam.topic.historyQos.depth = 2048;
                    subParam.topic.resourceLimitsQos.max_samples = 2048;
                    subParam.topic.resourceLimitsQos.allocated_samples = 2048;
                    subParam.qos.m_reliability.kind = eprosima::fastrtps::RELIABLE_RELIABILITY_QOS;                    
                    subParam.qos.m_durability.kind =eprosima::fastrtps::VOLATILE_DURABILITY_QOS;`

### Fast DDS version/commit

FastRTPS version : v1.7.x

### Platform/Architecture

Ubuntu Focal 20.04 amd64, Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

If I attached to gdb and put the breakpoint at write API of publisher for the same process at frequency 25ms, and hit next from gdb to execute write API of the publisher, it could able to send message to subscriber running in another application.
When I run independently without using gdb and not putting a breakpoint at the write API of the publisher for 25ms, it doesn't send a message to the subscriber running in another application, and the write API of the publisher doesn't throw any exception or any null pointer.
I am suspecting some bug in write API of the publisher at higher frequencies processing along with multiple pubs and subs.

### Network traffic capture

I have captured network traffic using Wireshark rtps support for the filter : **rtps.param.topicName == dds_method_call_setCompValveCommand** for both frequencies 25 ms and 250ms .

25ms case : 

                   Incase of 25 ms , I dont see any message sent for topic : "dds_method_call_setCompValveCommand".

![25ms](https://user-images.githubusercontent.com/97937609/182353745-6cd8b58e-3ad5-46bb-aec8-e9720a16dbd0.PNG)

250ms case:

                   Whereas in case of 250ms , I see communication b/w them for topic  "dds_method_call_setCompValveCommand".
![250ms](https://user-images.githubusercontent.com/97937609/182353754-45865fc1-1ff1-4f6b-afa2-be0f3869c3f5.PNG)

Could not able to attach .pcapng files captured as github doesnt allow them. If you want them, let me know a medium through which I can send them to you. Meanwhile I am checking using latest FastDDS stable version.
Please let me know if you need any details.Thanks in advance.

**Comment by ramcharan-palnati** [comment] 2022-08-11 04:28
Could any one help me out here. Please let me know if you need any info .

**Comment by EduPonz** [comment] 2022-08-11 09:59
Hi @ramcharan-palnati,

I'm afraid that v1.7 is not supported any more (see [RELEASE_SUPPORT.md](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md)). Did you manage to check with the latest Fast DDS? In any case, we'd need more info to replicate your scenario, such as whether the participants run in the same process/host or not, number of publishers and subscribers, etc. Another key aspect would be the data type definition. All in all, we would need a reproducer for your issue.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-10-27 13:26
I am going to proceed and close this issue as more information was required and it has not been provided. Feel free to reopen if the issue is still happening providing the required information to be able to reproduce and study the reported issue.

**Closed by JLBuenoLopez-eProsima** 2022-10-27 13:26 UTC
Labels: need more info
