### ISSUE TITLE
utf-8 error

### ISSUE THREAD

**Issue by Autostone-c** [eProsima/Fast-DDS#4345] opened 2024-02-01 01:27 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

git clone ros2_humble

### Current behavior

oepneuler 22.03
python: 3.9.9

![image](https://github.com/eProsima/Fast-DDS/assets/50130211/1fde9859-46f4-4344-9e2d-715788aced25)

### Steps to reproduce

colcon build 

### Fast DDS version/commit

ros2 humble

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4

**Comment by EduPonz** [comment] 2024-02-01 06:08
Hi @Autostone-c, thanks for using Fast DDS!

I'm afraid I'm going to close this issue for several reasons:

1. oepneuler is not a supported platform for Fast DDS (not is it for ROS 2 Humble), which means thing may or not may not work, but are certainly not expected to work (it is not a requirement).
2. IMO, the trace points more in the direction of colcon/CMake support, but I could be wrong as I haven't tried to reproduce this error. If the error is caused by the python-colcon interaction, you can always build Fast DDS with CMake directly.
3. If you're attempting to build ROS 2 and there is something not working when doing so, I think the place to report it would be [ros2/ros2](https://www.github.com/ros2/ros2). I understand that you opened the issue here because the failure was on the `fastrtps` packages, but the trace shows an attempt from `colcon_cmake` to parse the CMakeLists.txt file. Under the supported platforms and correct CMake versions, Fast DDS builds correctly.

If you have more insight into the matter, or are willing to contribute with an edit to the offending CMake file, please feel free to re-open this issue or submit a PR, we'll be happy to take a look at it.

**Closed by EduPonz** 2024-02-01 06:08 UTC
Labels: triage
