### ISSUE TITLE
How to use dynamic network interfaces ? [13545]

### ISSUE THREAD

**Issue by Barry-Xu-2018** [eProsima/Fast-DDS#2421] opened 2022-01-21 06:32 UTC
Refer to manual [dynamic-network-interfaces](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/dynamic_network_interfaces/dynamic_network_interfaces.html#dynamic-network-interfaces), I modify [example code](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExample).   

The changes as below: 
1.  
https://github.com/eProsima/Fast-DDS/blob/378e34e626a45f55ff38069dca9fbcfe9065ea0b/examples/C%2B%2B/DDS/HelloWorldExample/HelloWorldPublisher.cpp#L48
Change to 
```c++
participant_ = DomainParticipantFactory::get_instance()->create_participant(0, PARTICIPANT_QOS_DEFAULT);
```

2.  
https://github.com/eProsima/Fast-DDS/blob/378e34e626a45f55ff38069dca9fbcfe9065ea0b/examples/C%2B%2B/DDS/HelloWorldExample/HelloWorldPublisher.cpp#L122-L137

```c++
    if (samples == 0)
    {
        while (!stop_)
        {
           //-------------New added code ------------------------
            if (new_network_interface_ready)   // Set by other thread. 
            {
                // Notify Fast DDS a new network interface is available
                participant_->set_qos(PARTICIPANT_QOS_DEFAULT);
            }
           //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

            if (publish(false))
            {
                std::cout << "Message: " << hello_.message() << " with index: " << hello_.index()
                          << " SENT" << std::endl;
            }
            std::this_thread::sleep_for(std::chrono::milliseconds(sleep));
        }
    }
```

`new_network_interface_ready` is set while new network interface is ready (which means IP address is assigned.).

I run publisher by `DDSHelloWorldExample publisher 0`.   
After waiting 10  seconds, plugin USB Wi-Fi adapter.   
After this new Wi-Fi interface is assigned IP address, I wait 10 seconds.   
On other PC which is located at the same network of Wi-Fi adapter, I start subscribers program. But after wait for long time, subscriber still cannot  connect to publisher.   
BTW, I confirm `participant_->set_qos(PARTICIPANT_QOS_DEFAULT);` is executed, and it returns OK.  

Who can help to guide how to use this interface ? Thanks in advance.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-01-21 08:10
Hi @Barry-Xu-2018,

At first look it seems that you are using the interface correctly. However I would like to clarify a couple of points:

1. `new_network_interface_ready` flag is set in another thread that detects a new interface is available. When is this flag set to false? Is `set_qos` called permanently once the new interface is ready? The reason I ask is because I do not know when the OS considers the interface to be ready (you say that it is when an IP address has been assigned) so maybe it is a timing issue. In my experience while testing this feature, connecting a WiFi network interface took a longer time to be detected in Fast DDS than if an Ethernet interface is enabled.
2. Which platform/architecture and OS are you using? As this feature is OS-depending this info will also be helpful.
3. Also, it would be helpful if you can provide us, if possible, with a network traffic capture while trying to run this feature, specifically of the DATA(P) packets.
4. Finally, enabling the Info level of our log module can also provide some useful information. In order to enable Log Infos, you should build our library with the CMake options `LOG_NO_INFO=OFF` and `FASTDDS_ENFORCE_LOG_INFO=ON` (in case that you are building in a non-debug mode). Otherwise, it would already be enabled. In order to get the log messages, please configure the log module following the commands below:

```
Log::SetVerbosity(eprosima::fastdds::dds::Log::Info);
Log::SetCategoryFilter(std::regex("(RTPS_PARTICIPANT)"));
```

**Comment by Barry-Xu-2018** [comment] 2022-01-21 09:05
Hi @JLBuenoLopez-eProsima,  

> 1. new_network_interface_ready flag is set in another thread that detects a new interface is available. When is this flag set to false? Is set_qos called permanently once the new interface is ready? The reason I ask is because I do not know when the OS considers the interface to be ready (you say that it is when an IP address has been assigned) so maybe it is a timing issue. In my experience while testing this feature, connecting a WiFi network interface took a longer time to be detected in Fast DDS than if an Ethernet interface is enabled.

My bad.  I miss some code.  
```c++
           //-------------New added code ------------------------
            if (new_network_interface_ready)   // Set by other thread. 
            {
                new_network_interface_ready = false;

                // Notify Fast DDS a new network interface is available
                participant_->set_qos(PARTICIPANT_QOS_DEFAULT);
            }
           //^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Note that ` new_network_interface_ready = false;` is pseudo code. It needs to consider race condition.   

> connecting a WiFi network interface took a longer time to be detected

Yes. I use Netlink to get notification from kernel on IP address assigned to a new network interface.  

> 2. Which platform/architecture and OS are you using? As this feature is OS-depending this info will also be helpful.

My test environment is Ubuntu 20.04 (amd64).

> 3. Also, it would be helpful if you can provide us, if possible, with a network traffic capture while trying to run this feature, specifically of the DATA(P) packets.

Okay. I will record network traffic. 

> 4. Finally, enabling the Info level of our log module can also provide some useful information. In order to enable Log Infos, you should build our library with the CMake options LOG_NO_INFO=OFF and FASTDDS_ENFORCE_LOG_INFO=ON (in case that you are building in a non-debug mode). Otherwise, it would already be enabled. In order to get the log messages, please configure the log module following the commands below:

Okay.  
[0121_01.log](https://github.com/eProsima/Fast-DDS/files/7911807/0121_01.log)  
In the above log, you will find `+++ Update Fast DDS on new network interface` which is output before calling `participant_->set_qos(PARTICIPANT_QOS_DEFAULT);`.   
You also find notification with the same info can be gotten more than once. But I only deal with the notification of first time.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-01-21 09:43
Thanks, @Barry-Xu-2018!

I think it could be a timing issue. You are calling `set_qos` only once, when the Netlink tool is notified that the network interface has been assigned an IP address. Internally, when you call `set_qos`, Fast DDS is calling [`IPFinder::getIPs`](https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/utils/IPFinder.cpp#L156) which is using `getifaddrs` and checking that the `IFF_RUNNING` flag is set. Maybe, even though Netlink considers the interface to be running, this flag is not yet set and thus, Fast DDS will not start using the new network interface.

In order to check if this is the issue, maybe you can keep the `new_network_interface_ready` flag set to true so that the `set_qos` is always called. This is not optimal but it could serve to check if the communication is established at some point.

**Comment by Barry-Xu-2018** [comment] 2022-01-21 09:59
@JLBuenoLopez-eProsima 

> I think it could be a timing issue. You are calling set_qos only once, when the Netlink tool is notified that the network interface has been assigned an IP address. Internally, when you call set_qos, Fast DDS is calling IPFinder::getIPs which is using getifaddrs and checking that the IFF_RUNNING flag is set. Maybe, even though Netlink considers the interface to be running, this flag is not yet set and thus, Fast DDS will not start using the new network interface.

Thanks for your information. It is very useful. 

> In order to check if this is the issue, maybe you can keep the new_network_interface_ready flag set to true so that the set_qos is always called. This is not optimal but it could serve to check if the communication is established at some point.

I try to call `set_qos` after 20 seconds while new_network_interface_ready is set.    
But also doesn't work.    
Anyway, I will further investigate this.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-01-24 08:09
Hi, @Barry-Xu-2018,

Any news about the issue? We have thought about another explanation why your use case may be not working. If both Fast DDS applications have started without network interfaces, the automatically generated GUID prefix (that takes into account the available network interfaces) will be the same for both machines (because both will use localhost, not being any other network interface). Consequently, if this is the case, the applications will be trying to communicate using Shared Memory Transport instead of UDP, and being in different machines, this would not be possible.

**Comment by Barry-Xu-2018** [comment] 2022-01-24 08:58
@JLBuenoLopez-eProsima 

> We have thought about another explanation why your use case may be not working. If both Fast DDS applications have started without network interfaces, the automatically generated GUID prefix (that takes into account the available network interfaces) will be the same for both machines (because both will use localhost, not being any other network interface). Consequently, if this is the case, the applications will be trying to communicate using Shared Memory Transport instead of UDP, and being in different machines, this would not be possible.

Thank you very much for the information!  
For my test environment, publisher and subscriber are located at different device separately after calling `set_qos(PARTICIPANT_QOS_DEFAULT)` 

I am debugging code and find `metatrafficMulticastLocatorList` and `metatrafficUnicastLocatorList`  are all nonempty. 
https://github.com/eProsima/Fast-DDS/blob/5fd0462c92af132645258f2e1847731506209942/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L1168-L1178

So `IPFinder::getIPs` is never called.   
Do you any suggestion ?

**Comment by JLBuenoLopez-eProsima** [comment] 2022-01-26 06:24
Hi @Barry-Xu-2018,

We are looking into the feature and we have seen that it is not as thoroughly tested as we thought and that it needs some rework. We are issuing a PR ASAP and fix this feature for the next patch release 2.5.1. Sorry for the inconvenience and thanks for letting us know your issues with this feature. I will keep you posted!

**Comment by Barry-Xu-2018** [comment] 2022-01-26 06:45
Hi @JLBuenoLopez-eProsima,

Thanks for your information.  
After fixing this feature, I will try again.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-02-07 07:24
Hi @Barry-Xu-2018,

I have just issued #2468 that fixes the dynamic network interfaces feature. Can you give it a try and tell me if it works also for you? Thanks!

**Comment by Barry-Xu-2018** [comment] 2022-02-08 09:03
Hi @JLBuenoLopez-eProsima,

Sorry for the delay in replying.  I just came back from vacation.    
#2468 can make feature work well in my environment.   
Thank you for your hard work 👍

**Comment by Barry-Xu-2018** [comment] 2022-02-18 06:32
@JLBuenoLopez-eProsima   

I find a new problem.  
If network change on subscriber side,  after calling `participant_->set_qos(PARTICIPANT_QOS_DEFAULT);`, no message can be received.   

Test steps:  
1. publish message on Host A
2. subscriber is launched on Host B (plug-out network cable). 
3. plugin network cable on Host B
4. subscriber call `participant_->set_qos(PARTICIPANT_QOS_DEFAULT);` 
    After this step, terminal in subscriber side show "Subscriber matched."  
    Terminal in publisher side show "Publisher matched."  
    But no message is received.

Could you help to check it ?

**Comment by MiguelCompany** [comment] 2022-02-18 06:35
@Barry-Xu-2018 Has the subscriber `TRANSIENT_LOCAL` durability? Because if it is `VOLATILE` this would be the expected behavior.

**Comment by Barry-Xu-2018** [comment] 2022-02-18 07:06
@MiguelCompany 

Publisher send message continuously. But subscriber cannot get following messages (After call set_qos).  I mean that new messages from publisher cannot be received.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-02-18 07:31
Hi @Barry-Xu-2018,

That is really weird. When I was fixing the feature I was testing just with a test case similar to the one you just described. On one side a Raspberry Pi (Host A) was publishing continuously. In order to launch the publisher, I was connected to the Raspberry through an Ethernet cable so the Publisher was launched with two network interfaces up (the Ethernet one and the WiFi).
After plugging the Ethernet cable out, I launched the Subscriber in my local laptop (Host B). In this case, the Subscriber was launched with the WiFi interface enabled (but connected to a different WiFi network) so no discovery nor communication was established between Publisher and Subscriber.
After plugging the Ethernet cable (and waiting some time for the OS to upload and assign an IP to the network interface) discovery happened (as in your case), and afterwards messages were received.
Today I am working from home so I cannot recheck but Monday morning I will give it a try again and see if I can reproduce your issue. In the meantime, all additional information you can provide us would be surely helpful:

* Initial network interfaces for both Participants (in case there is a corner case where the initial network interfaces affect)
* Initial QoS settings (if applicable, and if the QoS are modified at a later point, also which ones and in which way)
* Logging information similar to the one you provided several weeks ago (it might prove useful and give a hint about the issue)

I assume you are still using Ubuntu 20.04 (amd64).
Thanks for your help!

**Comment by EduPonz** [comment] 2022-02-22 11:19
Hi @Barry-Xu-2018 

Lots of thanks for your thorough reports and investigation. We have decided to refactor the feature for Fast DDS v2.6.0 (due mid-March), we'll take into account your use-cases for our testing. Since the feature as-is has limited support already, I'm closing this ticket for now. We'll keep you posted with the refactor so you can give it another go there and then. Thanks for your help so far!

**Closed by EduPonz** 2022-02-22 11:19 UTC
