### ISSUE TITLE
DDSDynamicHelloWorldExample dosn't work

### ISSUE THREAD

**Issue by 1529825778** [eProsima/Fast-DDS#3132] opened 2022-12-03 13:45 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

the subscriber will receive some message when publisher run 

### Current behavior

there is no thing happening when I run subscriber first , then run publisher

### Steps to reproduce

in  console 1: ./DDSDynamicHelloWorldExample subscriber
in another console: ./DDSDynamicHelloWoldExample publisher
![Uploading 截图 2022-12-03 21-43-35.png…]()

### Fast DDS version/commit

2.7.1

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4

### Additional context

ubuntu 22.04

**Comment by 1529825778** [comment] 2022-12-04 07:11
I try it in another computer whith ubuntu 20.04,it works.  It's because that 22.04 does't support it？

**Comment by EduPonz** [comment] 2022-12-04 07:50
Hi @1529825778 , 

I just run the example in 22.04 and worked without problems for me. From your report, I understand that the following is happening to you, please correct me if I'm wrong:

1. You run the publisher which
2. You run the subscriber
3. The publisher starts sending messages
4. The subscriber starts receiving messages, but the first one (or maybe two) are not received

If that is the case, this is due to the `DurabilityQosPolicy` configuration, which the example leaves as default  (`TRANSIENT_LOCAL` for DataWriters, `VOLATILE` for DataReaders). What happens is that the DataWriters starts sending messages right after discovering the DataReader, but since the DataReader has not yet discovered the DataWriter, Fast DDS will discard those messages until the DataReader matches de DataWriter. Changing the subscriber application so that the DataReader is configured as `RELIABLE` and `TRANSIENT_LOCAL` should produce the behaviour you were expecting.

If the sequence I described is correct, please consider closing this ticket as it is not an issue in Fast DDS nor in the example. Else please provide more information on what is exactly happening, how to reproduce it step by step, and what would have you expected the behaviour to be.

**Comment by 1529825778** [comment] 2022-12-04 10:21
i download the source and compile it again, and have no problem now,  there may be something wrong the first time I installed it, thank you.

**Closed** 2022-12-04 10:22 UTC
Labels: need more info
