### ISSUE TITLE
Fast-DDS subscriber throws exception when OpenDDS publisher transmits a "key" message [9817]

### ISSUE THREAD

**Issue by dennisschagt** [eProsima/Fast-DDS#1523] opened 2020-10-27 15:52 UTC
It looks like there is an incompatibility between Fast-DDS and OpenDDS.
When setting up an OpenDDS publisher with a Fast-DDS subscriber, Fast-DDS often throws an exception when the first sample is published.

I can also reproduce this with the ShapesDemo.

## Steps to Reproduce
1. Start the OpenDDS ishapes application. It can be found in their repo ([examples/DCPS/ishapes)](https://github.com/objectcomputing/OpenDDS/tree/master/examples/DCPS/ishapes). I build it (tag: DDS-3.14) using `./configure --qt --tests "--configh=#define ACE_LACKS_SYS_SYSCTL_H" && make -j8` and run it using `source ./setenv.sh && ./examples/DCPS/ishapes/ishapes`.
2. Start eProsima's ShapesDemo application. I build (tag: v2.0.1) and run it using [the instructions in its README](https://github.com/eProsima/ShapesDemo/tree/8f5e26d8add3ba10f24e8a7a22d57114269877b9#user-content-installation-from-sources).
3. In eProsima's ShapesDemo, click "Subscribe" -> "Ok" (subscribes to "SQUARE" topic).
4. In OpenDDS's ishapes application, change the shape (dropdown) option to "Square" and click Publish

Order is important. If changing the order of steps 3 and 4, the ShapesDemo works as expected.

## Expected Behavior
The ShapesDemo visualizes the data which is published on the "SQUARE" topic.

## Current Behavior
The ShapesDemo terminates with the following output:
```
terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException'
  what():  Not enough memory in the buffer stream
Aborted (core dumped)
```

## System information

- Fast-DDS version: v2.0.1
- OS: Arch Linux
- Network interfaces: enp0s31f6 (192.168.2.2 in the included Wireshark capture)

## Additional context
Backtrace when running ShapesDemo with gdb:
![image](https://user-images.githubusercontent.com/4629607/97324485-2b7eca00-1872-11eb-9ae3-b7ed5a6cdc7c.png)

It looks like Fast-DDS sometimes crashes when `eprosima::fastrtps::SubscriberImpl::takeNextData()` is called.
From what I understand, this happens after receiving an RTPS DATA submessage with the "Serialized Key" flag set.
Such a message is also visible in the attached Wireshark capture (can be found with Wireshark display filter `rtps.flag.data.serialized_key == 1`).
![image](https://user-images.githubusercontent.com/4629607/97325512-603f5100-1873-11eb-868c-23ede1b3a469.png)

The attached Wireshark capture contains the packets transmitted between two hosts, one running eProsima's ShapesDemo (IP: 192.168.2.2), the other running OpenDDS's ishapes application (IP: 192.168.2.50).
All packets matching the Wireshark filter `rtps` are included, all other packets have been filtered out.

## Additional resources
- Wireshark capture: [wireshark.zip](https://github.com/eProsima/Fast-DDS/files/5446320/wireshark.zip)

**Comment by pavelpgt** [comment] 2020-12-09 15:59
Hi dennisschagt. I have just tested the problem with FastDDS and OpenDDS on Windows 10 and the problem is the same. 
I have used current prebuild ShapesDemo-OpenDDS-3.14-Windows and ShapesDemo-FastDDS-2.0.1. FastDDS Shapes Demo crashes when I subscribe in FastDDS Shapes Demo first and then publish something in OpenDDS ShapesDemo.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 10:24
Sorry @dennisschagt,

Fast DDS 2.0.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). I suggest you retest using the latest version of Fast DDS and Shapes Demo. Shapes Demo application was upgraded to use the new DDS specification compliant API in eProsima/ShapesDemo#37. Fast DDS release testing also checks interoperability between eProsima Shapes Demo and other vendors, including OpenDDS. The latest releases has not shown the mentioned issue so it might have been solved already. I am going to close the issue but feel free to reopen if you can reproduce the issue with the newest versions of Fast DDS and Shapes Demo.

**Closed by JLBuenoLopez-eProsima** 2022-03-01 10:24 UTC
