### ISSUE TITLE
Maximum length problem of generated code, function of getMaxCdrSerializedSize [13315]

### ISSUE THREAD

**Issue by cloudjacky** [eProsima/Fast-DDS#2366] opened 2021-12-21 09:22 UTC
## Expected Behavior

For strings, or vectors, there should be no limit to their max length

## Current Behavior

Now they are limited to more than 255 bytes

## Steps to Reproduce

1.  Use HelloWorldExample of Fast dds. The path is Fast-DDS/examples/C++/HelloWorldExample
2.  When the length of the sent data exceeds 300, the data send fails.

## System information

ubuntu 18.04

- Fast-RTPS version: 
- OS: 
- Network interfaces: 
                      
- ROS2: 
        

## Additional context

size_t HelloWorld::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4) + 255 + 1;  ?????????

    return current_alignment - initial_alignment;
}

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by JLBuenoLopez-eProsima** [comment] 2021-12-21 10:24
Hi @cloudjacky:

This is related with the [MemoryManagementPolicy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#memorymanagementpolicy). By default, Fast DDS uses `PREALLOCATED_MEMORY_MODE` to avoid dynamic allocations (please refer to [Fast DDS documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#rtpsendpointqos)). Thus, in case of unbounded types such as `vector` or `string`, Fast DDS reserves up to 255 elements. If the `MemoryManagementPolicy` is not changed to another kind that allows dynamic allocations, the data sending of unbounded types with more than 255 elements is going to fail.

Therefore, the behavior you are describing is in fact the expected behavior and not a bug. Please, let me know if changing the `MemoryManagementPolicy` solves your issue and, if so, please remember to close it.

**Comment by JLBuenoLopez-eProsima** [comment] 2021-12-21 10:33
This issue was already answered in #2330, so I am closing it.

**Closed by JLBuenoLopez-eProsima** 2021-12-21 10:33 UTC
Labels: duplicate
