### ISSUE TITLE
Reader and writer within different domains are matched each other using a same discovery server

### ISSUE THREAD

**Issue by chunyisong** [eProsima/Fast-DDS#3645] opened 2023-07-01 02:16 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Reader and writer with different domain id will never be matched each other using a same discovery server.
All Entities  will using TCPV4.

### Current behavior

Reader and writer with different domain id will never be matched each other using a same discovery server.
All Entities  will using TCPV4

### Steps to reproduce

All Entities  will only using TCPV4 to transport user and meta data.
1. Start a DiscoverServer 0 using TCPV4 whih command:
`
 fastdds discovery -i 0 -x participant_discovery_server_profile@discovery_server_profile.xml
`
3. In a host,Create and start a DataReader subscribing Topic_0 within a DomainParticipant in domain id 0 connecting to DiscoverServer 0.
4. In another host,Create and start a DataWriter publishing Topic_0 within a DomainParticipant in domain id 1 connecting to DiscoverServer 0.
5. Then the reader in domain 0 and the writer in domain 1 will be matched!

### Fast DDS version/commit

2.10.1

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

### XML configuration file

```xml
discovery_server_profile.xml

<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="file:///Fast-DDS_ws/src/fastrtps/resources/xsd/fastRTPS_profiles.xsd"?>
<dds>
    <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
        <transport_descriptors>
            <transport_descriptor>
                <transport_id>transport_tcp4_ds</transport_id>
                <type>TCPv4</type>
                <maxMessageSize>1500</maxMessageSize>
                <interfaceWhiteList>
                    <address>172.16.0.202</address>
                    <!-- <address>10.8.8.70</address> -->
                </interfaceWhiteList>
                <keep_alive_timeout_ms>15000</keep_alive_timeout_ms> -->
                <listening_ports>
                    <port>17480</port>
                </listening_ports>
                <enable_tcp_nodelay>true</enable_tcp_nodelay>
                <calculate_crc>false</calculate_crc>
                <check_crc>false</check_crc>
            </transport_descriptor>
        </transport_descriptors>
        <participant profile_name="participant_discovery_server_profile">
            <domainId>20</domainId>
            <rtps>
                <participantID>20</participantID>
                <!-- <propertiesPolicy>
                    <properties>
                        <property>
                            <name>fastdds.ignore_local_endpoints</name>
                            <value>true</value>
                        </property>
                    </properties>
                </propertiesPolicy> -->
                <useBuiltinTransports>false</useBuiltinTransports>
                <userTransports>
                    <!-- <transport_id>transport_shm</transport_id> -->
                    <transport_id>transport_tcp4_ds</transport_id>
                    <!-- <transport_id>transport_udp4</transport_id> -->
                </userTransports>
                <builtin>
                    <avoid_builtin_multicast>true</avoid_builtin_multicast>
                    <discovery_config>
                        <discoveryProtocol>SERVER</discoveryProtocol>
                        <EDP>SIMPLE</EDP>
                        <leaseDuration>
                            <sec>30</sec>
                            <nanosec>0</nanosec>
                        </leaseDuration>
                        <leaseAnnouncement>
                            <sec>15</sec>
                            <nanosec>0</nanosec>
                        </leaseAnnouncement>
                        <initialAnnouncements>
                            <count>5</count>
                            <period>
                                <sec>2</sec>
                                <nanosec>0</nanosec>
                            </period>
                        </initialAnnouncements>
                    </discovery_config>
                    <!-- Set SERVER's listening locator for PDP -->
                    <metatrafficUnicastLocatorList>
                        <locator>
                            <tcpv4>
                                <port>17480</port>
                                <address>172.16.0.202</address>
                            </tcpv4>
                        </locator>
                    </metatrafficUnicastLocatorList>
                </builtin>
            </rtps>
        </participant>
    </profiles>
</dds>
```
```


### Relevant log output

_No response_

### Network traffic capture

_No response_

**Comment by JLBuenoLopez-eProsima** [comment] 2023-07-03 05:57
Thanks @chunyisong for your contribution!

This is not a bug in the Discovery Server implementation but a design decision. I have created eProsima/Fast-DDS-docs#517 to clarify this point in Discovery Server mechanism documentation. I am going to proceed and close this issue.

**Closed by JLBuenoLopez-eProsima** 2023-07-03 05:57 UTC
Labels: invalid
