### ISSUE TITLE
TCP connection failed after entity dropped and reconnection. [13707]

### ISSUE THREAD

**Issue by ilikecola** [eProsima/Fast-DDS#2312] opened 2021-11-10 15:23 UTC
## Expected Behavior
TCP connection can work after long time connection lost.

## Current Behavior
After a TCP connection between pub/sub works perfectly, manually disconnect cable of pub side which cause connection lost.
within 5 mintues ,reconnect the cable and connection is recovered , all entities work again.However,10 mintues later, reconnect the cable and connection between pub/sub is recovered but messages cannot be sent.

## Steps to Reproduce
1.start pub and sub
2.disconnect cable of pub side causing connection lost
3.10 mintues later, reconnect the cable

## System information
- Fast-RTPS version: 2.4.x
- OS: Ubuntu 20.04

## Additional resources
```
<data_writer profile_name="datawriter_profile">
                        <topic>
                                <historyQos>
                                        <kind>KEEP_LAST</kind>
                                        <depth>1</depth>
                                </historyQos>
                        </topic>
                        <qos>
                                <reliability>
                                        <kind>BEST_EFFORT</kind>
                                </reliability>
                                <durability>
                                        <kind>VOLATILE</kind>
                                </durability>
                                <publishMode>
                                        <kind>ASYNCHRONOUS</kind>
                                </publishMode>
                        </qos>
                        <historyMemoryPolicy>DYNAMIC_REUSABLE</historyMemoryPolicy>
</data_writer>
```

```
<participant profile_name="participant_profile">
                        <domainId>80</domainId>
                        <rtps>
                                <userTransports>
                                        <transport_id>tcp2_transport</transport_id>
                                </userTransports>
                                <useBuiltinTransports>false</useBuiltinTransports>
                                <builtin>
                                        <initialPeersList>
                                                <locator>
                                                        <tcpv4>
                                                                <address>xxx.xxx.xxx.xxx</address>
                                                                <physical_port>6300</physical_port>
                                                        </tcpv4>
                                                </locator>
                                        </initialPeersList>
                                </builtin>
                                <name>ZX0001</name>
                        </rtps>
</participant>
```
debug logs:
```
[37;1m2021-11-10 14:05:37.219 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending relevant changes as DATA/DATA_FRAG messages[34;1m -> Function [36madd_data_frag[m
[37;1m2021-11-10 14:05:37.219 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending INFO_TS message[34;1m -> Function [36madd_info_ts_in_buffer[m
[37;1m2021-11-10 14:05:37.219 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending relevant changes as DATA/DATA_FRAG messages[34;1m -> Function [36madd_data_frag[m
[37;1m2021-11-10 14:05:37.219 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending INFO_TS message[34;1m -> Function [36madd_info_ts_in_buffer[m
[37;1m2021-11-10 14:05:37.871 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending relevant changes as DATA/DATA_FRAG messages[34;1m -> Function [36madd_data[m
[37;1m2021-11-10 14:05:37.871 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending INFO_TS message[34;1m -> Function [36madd_info_ts_in_buffer[m
[37;1m2021-11-10 14:05:37.871 [32;1m[[37;1mRTCP_MSG[32;1m Info] [37mSend [OPEN_LOGICAL_PORT_REQUEST] LogicalPort: 27410[34;1m -> Function [36msendOpenLogicalPortRequest[m
[37;1m2021-11-10 14:05:37.871 [32;1m[[37;1mRTCP_MSG[32;1m Info] [37mSend [OPEN_LOGICAL_PORT_REQUEST] LogicalPort: 27414[34;1m -> Function [36msendOpenLogicalPortRequest[m
[37;1m2021-11-10 14:05:37.871 [32;1m[[37;1mRTCP_MSG[32;1m Info] [37mSend [OPEN_LOGICAL_PORT_REQUEST] LogicalPort: 27416[34;1m -> Function [36msendOpenLogicalPortRequest[m
[37;1m2021-11-10 14:05:38.220 [32;1m[[37;1mDATA_WRITER[32;1m Info] [37mWriting new data[34;1m -> Function [36mwrite[m
[37;1m2021-11-10 14:05:38.221 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mCreating new change[34;1m -> Function [36mnew_change[m
[37;1m2021-11-10 14:05:38.221 [32;1m[[37;1mRTPS_WRITER_HISTORY[32;1m Info] [37mChange 29 added with 81304 bytes[34;1m -> Function [36madd_change_[m
[37;1m2021-11-10 14:05:38.222 [32;1m[[37;1mRTPS_HISTORY[32;1m Info] [37mTC57CIM::JiangSu::BreakerModule::BreakerReadingProfile Change 29 added with key: 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0 and 81304 bytes[34;1m -> Function [36madd_pub_change[m
[37;1m2021-11-10 14:05:38.222 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending relevant changes as DATA/DATA_FRAG messages[34;1m -> Function [36madd_data_frag[m
[37;1m2021-11-10 14:05:38.222 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending INFO_TS message[34;1m -> Function [36madd_info_ts_in_buffer[m
[37;1m2021-11-10 14:05:38.222 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending relevant changes as DATA/DATA_FRAG messages[34;1m -> Function [36madd_data_frag[m
[37;1m2021-11-10 14:05:38.222 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending INFO_TS message[34;1m -> Function [36madd_info_ts_in_buffer[m
[37;1m2021-11-10 14:05:39.222 [32;1m[[37;1mDATA_WRITER[32;1m Info] [37mWriting new data[34;1m -> Function [36mwrite[m
[37;1m2021-11-10 14:05:40.871 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending relevant changes as DATA/DATA_FRAG messages[34;1m -> Function [36madd_data[m
[37;1m2021-11-10 14:05:40.871 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending INFO_TS message[34;1m -> Function [36madd_info_ts_in_buffer[m
[37;1m2021-11-10 14:21:24.615 [33;1m[[37;1mDEBUG[33;1m Warning] [37mError reading TCP header: Connection timed out[34;1m -> Function [36mReceive[m
[37;1m2021-11-10 14:21:24.615 [33;1m[[37;1mDEBUG[33;1m Warning] [37mFailed to send RTCP message (59036 of 65482 b): Broken pipe[34;1m -> Function [36msend[m
[37;1m2021-11-10 14:21:24.615 [32;1m[[37;1mRTCP[32;1m Info] [37mEnd PerformListenOperation TCPv4:[xxx.xxx.xxx.xxx]:6300[34;1m -> Function [36mperform_listen_operation[m
[37;1m2021-11-10 14:21:24.616 [31;1m[[37;1mRTCP[31;1m Error] [37mOpenning socket resolve: Host not found (authoritative)[34;1m -> Function [36mconnect[m
[37;1m2021-11-10 14:21:24.616 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending relevant changes as DATA/DATA_FRAG messages[34;1m -> Function [36madd_data[m
[37;1m2021-11-10 14:21:24.616 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mSending INFO_TS message[34;1m -> Function [36madd_info_ts_in_buffer[m
[37;1m2021-11-10 14:21:24.616 [32;1m[[37;1mRTPS_PDP[32;1m Info] [37m01.0f.de.77.dd.4f.c8.f4.01.00.00.00|0.0.1.c1[34;1m -> Function [36mremove_remote_participant[m
[37;1m2021-11-10 14:21:24.616 [32;1m[[37;1mRTPS_EDP[32;1m Info] [37m01.0f.de.77.dd.4f.c8.f4.01.00.00.00|0.0.4.4[34;1m -> Function [36munpairReaderProxy[m
[37;1m2021-11-10 14:21:24.618 [32;1m[[37;1mRTPS_WRITER[32;1m Info] [37mCreating new change[34;1m -> Function [36mnew_change[m
[37;1m2021-11-10 14:21:24.618 [32;1m[[37;1mRTPS_WRITER_HISTORY[32;1m Info] [37mChange 30 added with 84104 bytes[34;1m -> Function [36madd_change_[m
[37;1m2021-11-10 14:21:24.618 [32;1m[[37;1mRTPS_HISTORY[32;1m Info] [37mTC57CIM::JiangSu::BreakerModule::BreakerReadingProfile Change 30 added with key: 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0 and 84104 bytes[34;1m -> Function [36madd_pub_change[m
```

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 15:23
@ilikecola 

#2470 was merged some weeks ago and it might solve your issue. Would you mind checking against the latest Fast DDS release? The changes were also backported to all official supported releases of Fast DDS.

**Comment by JLBuenoLopez-eProsima** [comment] 2022-04-04 05:47
I am going to close this issue due to inactivity. A fix was merged a couple of months ago and no feedback has been received from the user. @ilikecola, please, feel free to reopen if the issue is still happening after applying changes in #2470.

**Closed by JLBuenoLopez-eProsima** 2022-04-04 05:47 UTC
