### ISSUE TITLE
Not working when building with CMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by CuiiGen** [eProsima/Fast-DDS#3981] opened 2023-11-02 00:44 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

DataReader can receive data from DataWriter.

### Current behavior

While it fails when building with CMAKE_BUILD_TYPE=Release

### Steps to reproduce

I have built and installed the Fast-DDS library and its dependencies from the source code.
Configuration and build with CMAKE_BUILD_TYPE=Release.
Run DataWriter and DataReader in two terminals.
DataReader cannot receive data from DataWriter.

### Fast DDS version/commit

467216b2142174a6cb90709ae39b53eaff2aaca6

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

**Comment by JLBuenoLopez-eProsima** [comment] 2023-11-02 06:16
@CuiiGen 

This use case is tested in Fast DDS nightly CI so I strongly doubt that the cause of not communicating is building in Release. Probably the cause is related to the QoS configuration or the network architecture. More information would be needed in order to be helpful.

**Comment by CuiiGen** [comment] 2023-11-06 08:21
@JLBuenoLopez-eProsima Thanks for your reply.
There is a zip file which is a sample project [TestDDS.zip](https://github.com/eProsima/Fast-DDS/files/13264113/TestDDS.zip).
It works well when built with CMAKE_BUILD_TYPE=Debug, while it doesn't with CMAKE_BUILD_TYPE=Release.
It's notable that the publisher and subscriber are both not running in the main thread of the program.
Thanks for your effort.

**Comment by CuiiGen** [comment] 2023-11-06 08:21
@JLBuenoLopez-eProsima Thanks for your reply.
There is a zip file which is a sample project [TestDDS.zip](https://github.com/eProsima/Fast-DDS/files/13264113/TestDDS.zip).
It works well when build with CMAKE_BUILD_TYPE=Debug, while it doesn't with CMAKE_BUILD_TYPE=Release.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-11-07 07:15
@CuiiGen 

I have been unable to build your code as it is linking statically. I have linked dynamically and everything works as expected. Can you provide some building instructions?

**Comment by CuiiGen** [comment] 2023-11-08 07:13
We have installed Fast-DDS and its dependencies according to the instructions on this [page](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html#cmake-installation).
The projects `Foonathan memory` and `Fast CDR` are configured and installed by the following commands
````
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr/local/" -DBUILD_SHARED_LIBS=OFF
sudo cmake --build . --target install
````
The project `Fast-DDS` is configured and built with
````
cmake ..  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr/local/" -DBUILD_SHARED_LIBS=OFF -DNO_TLS=ON -DSTRICT_REALTIME=ON -DSQLITE3_SUPPORT=OFF -DTHIRDPARTY=FORCE
sudo cmake --build . --target install
````
We'd like to link this library statically since we need the final executable target to be portable.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-11-08 08:38
Hi @CuiiGen 

I have reproduced your issue, but it is fixed by removing the `STRICT_REALTIME` option. I am modifying the issue title so it correctly describes the issue, and we will try to allocate some time to look into it.

**Comment by CuiiGen** [comment] 2023-11-08 12:26
![image](https://github.com/eProsima/Fast-DDS/assets/46126598/92f5349d-c98e-44db-89bb-27b48e3db029)

Thanks for your timely reply.
I have rebuild and install FastDDS but still not the same.
I'm quite puzzled why it's not working.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-11-08 13:05
Have you rebuilt without the STRICT_REALTIME option and are you still having the issue?

**Comment by CuiiGen** [comment] 2023-11-08 13:11
Yes, I have tried to reconfigure and build the project without the STRICT_REALTIME option or set it to OFF explicitly.
And unfortunately I still have the issue.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-11-08 13:50
Have you cleaned your build before building again? Sometimes, even reconfiguring is not enough for rebuilding to be triggered. Nevertheless, find attached the docker log where I built the workspace following your commands, only removing the STRICT_REALTIME CMake option from the configuring of Fast DDS:

- Line 1967: foonathan memory configuration
- Line 1973: foonathan memory build command
- Line 2576: Fast CDR configuration
- Line 2609: Fast CDR build command
- Line 3103: Fast DDS configuration: same command as provided but without the STRICT_REALTIME option.
- Line 3169: Fast DDS build command
- Line 4010: TestDDS configuration
- Line 4028: TestDDS build
- Line 4043: TestDDS execution successful.

[docker.log](https://github.com/eProsima/Fast-DDS/files/13297251/docker.log)

**Comment by CuiiGen** [comment] 2023-11-12 03:55
I have tried again and still had that issue.
Here is the log where I configured Fast-DDS and built the TestDDS project.
[cuiigen_bash.log](https://github.com/eProsima/Fast-DDS/files/13327096/cuiigen_bash.log)

- line 2: the Fast-DDS project is clean
- line 8: empty folder `build`
- line12: configure the project without `STRICT_REALTIME` option
- line 69: build and install Fast-DDS
- line 305: install and update the Fast-DDS library
- line 885: empty folder `buld`
- line 888: configure with -DCMAKE_BUILD_TYPE=Debug
- line 904: build the project
- line 949: run it successfully as expected
- line 941: remove the original build folder and make a new one
- line 958: configure with -DCMAKE_BUILD_TYPE=Release
- line 975: build the project
- line 990: run it and something unexpected occurs

I guess the executable target that you run is still built as Debug since you did not configure the project with `-DCMAKE_BUILD_TYPE=Release` explicitly, as shown in the line 4010 of the `docker.log` .

**Comment by JLBuenoLopez-eProsima** [comment] 2023-11-13 08:13
@CuiiGen 

You are correct. I incorrectly assumed that not defining the CMAKE_BUILD_TYPE variable would by default set it up as Release. I have reproduced your results, though I am afraid that in this case, it seems like the issue is in the application code and not in Fast DDS. Fast DDS built in Release mode is correctly working. I have checked that building an application over Fast DDS built statically and in release mode works as expected, using the HelloWorldExample. Instead of building your application, I have built the example using `CMAKE_BUILD_TYPE=Release` and I have checked that it works correctly.

**Comment by MiguelCompany** [comment] 2023-11-13 08:31
@CuiiGen I've taken a look at your application code, and I've found what your problem is.

The following lines on your `main()` function will do nothing when built with `CMAKE_BUILD_TYPE=Release`:

```c++
    // Initialize mypub mysub
    assert(mypub.init());
    assert(mysub.init());
```

See official C++ documentation for [assert](https://en.cppreference.com/w/cpp/error/assert) for an in-depth explanation

You should change your code like this:

```c++
    bool is_pub_init_ok = mypub.init();
    assert(is_pub_init_ok);
    bool is_sub_init_ok = mysub.init();
    assert(is_sub_init_ok);
```

**Comment by CuiiGen** [comment] 2023-11-14 00:38
Thank you all so much for helping me with this issue.
The bug in my application has been fixed with the advice of @MiguelCompany .

**Closed** 2023-11-14 06:11 UTC
Labels: invalid
