### ISSUE TITLE
Samples written on_publication_matched() by reliable writer CANNOT be delivered to the reliable reader reliably

### ISSUE THREAD

**Issue by sfzhang** [eProsima/Fast-DDS#3009] opened 2022-10-13 03:03 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

For `RELIABLE_RELIABILITY_QOS`, the samples written `on_publication_matched()` CAN be delivered to the reader reliably.

### Current behavior

For `RELIABLE_RELIABILITY_QOS`, the samples written `on_publication_matched()` **CANNOT** be delivered to the reader reliably.

### Steps to reproduce

Scenario 1:
1. Start writer on terminal. The writer will write sample in `on_publication_matched()`.
2. Start reader on anther terminal and it should receive the sample written by writer.
3. Press Ctrl-C to kill reader.
4. Now start reader again and press Ctrl-C to kill reader before it take the sample.
5. Repeat step 4 several times, reader will not receive the sample even if not been killed!.

Scenario 2:
1. Start writer on terminal. The writer will write sample in `on_publication_matched()`.
2. Start reader 1 on anther terminal and it should receive the sample written by writer.
3. Start reader 2 on anther terminal. reader 1 and 2 will receive the sample. As soon as reader 2 received sample, press q to let reader 2 exit.
4. Repeat  step 3 several times, reader 2 will not receive the sample again!

### Fast DDS version/commit

2.5.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### Additional context

From the output log, I find the problem happened if the new reader starts before writer unmatched the previous reader.

### Relevant log output

```shell
Scenario 1 log output:
1. writer

./writer 
Create writer successfully!
Press q/Q to exit: publication matched topic: HelloWorld, current_count: 1, current_count_change: 1
write() topic: HelloWorld
publication matched topic: HelloWorld, current_count: 2, current_count_change: 1
write() topic: HelloWorld
publication matched topic: HelloWorld, current_count: 3, current_count_change: 1
write() topic: HelloWorld
publication unmatched topic: HelloWorld, current_count: 2, current_count_change: -1
publication matched topic: HelloWorld, current_count: 3, current_count_change: 1
write() topic: HelloWorld
publication unmatched topic: HelloWorld, current_count: 2, current_count_change: -1
publication unmatched topic: HelloWorld, current_count: 1, current_count_change: -


2. reader

./reader
Create reader successfully!
Press q/Q to exit: subscription matched on topic: HelloWorld, current_count: 1, current_count_change: 1
on_data_available
take_next_sample() success: instance_state[Alive]
HelloWorld:
	id: 1
	name: helloworld
^C


./reader
Create reader successfully!
Press q/Q to exit: subscription matched on topic: HelloWorld, current_count: 1, current_count_change: 1
^C


./reader
Create reader successfully!
Press q/Q to exit: subscription matched on topic: HelloWorld, current_count: 1, current_count_change: 1
on_data_available
take_next_sample() success: instance_state[Alive]
HelloWorld:
	id: 1
	name: helloworld
^C

./reader
Create reader successfully!
Press q/Q to exit: subscription matched on topic: HelloWorld, current_count: 1, current_count_change: 1

```

**Comment by sfzhang** [comment] 2022-10-13 03:14
[helloworld.zip](https://github.com/eProsima/Fast-DDS/files/9770135/helloworld.zip)

**Comment by Mario-DL** [comment] 2022-12-01 07:09
Hi @sfzhang, 

There was a previous related issue #2423. This should have been fixed by https://github.com/eProsima/Fast-DDS/pull/2448. In fact, I was not able to reproduce it on 2.5.1.

**Closed by Mario-DL** 2022-12-01 07:09 UTC
Labels: duplicate
