### ISSUE TITLE
subscriber matched late can't receive message [13716]

### ISSUE THREAD

**Issue by sky-fire** [eProsima/Fast-DDS#2387] opened 2022-01-06 04:14 UTC
subscriber matched late can't receive message

## Expected Behavior
subscriber matched late can receive message

## Current Behavior
 I have 1 publisher and 6 subscriber,one subscriber is matched late,and I find it can't receive message correctly,I use wireshark to catch the packages,and I find the sbscriber have receive message with wrong seq_num, for example, the heartbeat message sent by publisher tell the subscriber change 0-2 is available, but the subscriber only receive change 0-3. It should be a timing problem，I found that every time an exception occurs, a big sequence num packet will be received after matching,after that the subscriber can't receive the correct message

## Steps to Reproduce

1.start 1 publisher and 6 subscriber
2.reboot and retry

## System information

- Fast-RTPS version: 
- OS: 
- Network interfaces: < lo (127.0.0.1)>

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by EduPonz** [comment] 2022-01-07 12:08
Hi @sky-fire ,

I would need a bit more info to figure out what the actual issue might be (Fast DDS version, QoS, etc.).

Which QoS are you setting in sending and receiving side? Can it be that you are configuring a BEST_EFFORT-TRANSIENT_LOCAL configuration. Mind that in newer Fast DDS versions, in order for TRANSIENT_LOCAL to take effect, the reliability must be set to RELIABLE (see [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html#durabilityqospolicy)).

**Comment by sky-fire** [comment] 2022-01-11 03:49
I have 1 publisher and 6 subscriber,one subscriber is matched late,and I find it can't receive message correctly,I use wireshark to catch the packages,and I find the sbscriber have receive message with wrong seq_num, for example, the heartbeat message sent by publisher tell the subscriber change 2 is available, but the subscriber only receive change 3. It should be a timing problem，I found that every time an exception occurs, a big sequence num packet will be received after matching, after that the subscriber can't receive the correct message, and the subscriber will drop the packet due to the wrong sequence number
the publisher is RELIABLE and VOLATILE，subscriber is the same，and Fast-RTPS version is 1.10.00
I just wonder if there are same question

**Comment by JLBuenoLopez-eProsima** [comment] 2022-03-01 10:42
Sorry @sky-fire,

Fast DDS (formerly known as FastRTPS) 1.10.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). Consequently, I am going to close the issue. If you try a newer and supported release and find that the problem is still happening, feel free to reopen.

**Closed by JLBuenoLopez-eProsima** 2022-03-01 10:42 UTC
Labels: need more info
