### ISSUE TITLE
[16785] The more and more participants are created, CPU usage and memory consumption are significantly increased even if no message is sent

### ISSUE THREAD

**Issue by Barry-Xu-2018** [eProsima/Fast-DDS#3163] opened 2022-12-20 07:15 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

If no messages are sent (only connection establishment between publisher and subscription), CPU usage and memory consumption should not be significantly increased 

### Current behavior

According to test result, CPU usage and memory consumption should not be significantly increased.

### Steps to reproduce

Test environment:

![image](https://user-images.githubusercontent.com/43591679/208599420-949e5a30-fc81-468e-a6d5-2cd00c64de16.png)

- Hardware
    - 2 RasPi 4  Boards
-  OS
    - ubuntu 22.04.1
-  ROS2
    -  rolling (setup refers to https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html)
-  Test codes
   - https://github.com/Barry-Xu-2018/test_multi_nodes_multi_pub_sub
     ```
     $ mkdir -p ros2_ws/src && cd ros2_ws/src
     $ git clone https://github.com/Barry-Xu-2018/test_multi_nodes_multi_pub_sub
     $ cd ..
     $ source /opt/ros/rolling/setup.bash
     $ colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release
     $ source install/setup.bash
     ```
     Run test program on one RasPi board as publisher
     ```
     $ ros2 run test_multi_nodes_multi_pub_sub multi_nodes_multi_pub -t 1 -p 1  # One node with one pulibsher for one topic
     $ ros2 run test_multi_nodes_multi_pub_sub multi_nodes_multi_pub -t 10 -p 1  # 10 nodes , each node has one publisher and  each publisher is corresponding to one topic. (That is, there are 10 topics)
     ```
     Run test program on another RasPi board as subscriber
     ```
     $ ros2 run test_multi_nodes_multi_pub_sub multi_nodes_multi_sub -t 1 -s 10 -n1s1 # Create 10 nodes and each node has one subscription. These 10 subscriptions are for one topic.
     $ ros2 run test_multi_nodes_multi_pub_sub multi_nodes_multi_sub -t 10 -s 10 -n1s1 # create 100 nodes and each node has one subscription. Evey 10 subscriptions are for one topic (That is, there are 10 topics)
     ```

- How to test
  After test program for subscription print "+++ All subscriptions connect publishers ! +++", it means each all connection are established between publisher and subscription. 
  And then run below command for 10 minutes to get CPU usage and memory consumption, 
  ```
  top -b -p TEST_PROGRAM_PID -d 0.5 > log
  ```
  Get CPU usage by  (ubuntu is my device name) and calculate the average
  ```
  $ grep 'ubuntu' | awk '{print $9}' 
  ```
  Get memory consumption by 
  ```
  $ grep 'ubuntu' | awk '{print $9}' 
  ```

In my environment, test result is

| Topic | CPU usage on pub side | CPU usage on sub side | Used memory on pub side (Byte) | Used memory on sub side  (Byte) |
|:--|:--|:--|:--|:--|
| 1  | 0.186% | 0.176% |  20192 | 31250  |
| 10  |  2.375% (10 nodes) | 4.36% (100 nodes) | 47536  | 268564 |
| 30  | 32.22% (30 nodes) |  98.82% (300 nodes) | 188856 | 1.6GB  |

Besides, I find 
As more and more node are created, the creation of nodes become slower and slower on sub side. (Special, while the number of created node is more than 200). Finally, the speed of creating a node and a subscription takes about 1~2 seconds.

For ros2, my knowledge is that one node is corresponding to one participant of DDS.

### Fast DDS version/commit

ros-rolling-fastrtps        2.8.0-1jammy.20221102.193253 

### Platform/Architecture

Ubuntu Focal 20.04 arm64, Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by fujitatomoya** [comment] 2022-12-20 18:44
@MiguelCompany actually we have tried with `cyclonedds` that can provide more efficient management, it does not really increase the consumption as endpoints increase. we can share this result if you guys need.

BTW, the following work-around would not be really options.

- [Static EDP](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/static.html#static-edp)
  - could be used, but really hard to define all the connectivity beforehand.
  - using DDS means for distributed application, this means use case for DDS is NOT static configuration basically.
  - describing all topology in xml will be hard to depict and maintain for scale and large system.
- [Discovery Server](https://www.eprosima.com/index.php/products-all/tools/eprosima-discovery-server)
  - new burden for user application since this is responsibility for user.
  - single point failure is not acceptable for distributed system, must be `fail independently`.
  - backup server can be standing by, but user burden could not be acceptable.

do you have any suggestion or idea? basically we would be able to tackle this problem to optimize discovery and EDP?

**Comment by Barry-Xu-2018** [comment] 2022-12-28 08:43
After using perf to check, I found there are many CPU consumption on send_periodic_heartbeat().
```
-   87.06%     0.00%  multi_nodes_mul  libfastrtps.so.2.9.0           [.] std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (eprosima::fastrtps::rtps::Re▒
     std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*> > >::_M_▒
     std::thread::_Invoker<std::tuple<void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*> >::operator()                    ▒
     std::thread::_Invoker<std::tuple<void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*> >::_M_invoke<0ul, 1ul>           ▒
     std::__invoke<void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*>                                                     ▒
   - std::__invoke_impl<void, void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*>                                          ▒
      - 87.06% eprosima::fastrtps::rtps::ResourceEvent::event_service                                                                                                 ▒
         - 87.04% eprosima::fastrtps::rtps::ResourceEvent::do_timer_actions                                                                                           ▒
            - 86.99% eprosima::fastrtps::rtps::TimedEventImpl::trigger                                                                                                ▒
               - 86.97% std::function<bool ()>::operator()                                                                                                            ▒
                  - 86.96% std::_Function_handler<bool (), eprosima::fastrtps::rtps::StatefulWriter::init(eprosima::fastrtps::rtps::RTPSParticipantImpl*, eprosima::fa▒
                     - 86.96% std::__invoke_r<bool, eprosima::fastrtps::rtps::StatefulWriter::init(eprosima::fastrtps::rtps::RTPSParticipantImpl*, eprosima::fastrtps:▒
                        - std::__invoke_impl<bool, eprosima::fastrtps::rtps::StatefulWriter::init(eprosima::fastrtps::rtps::RTPSParticipantImpl*, eprosima::fastrtps::▒
                           - 86.95% eprosima::fastrtps::rtps::StatefulWriter::init(eprosima::fastrtps::rtps::RTPSParticipantImpl*, eprosima::fastrtps::rtps::WriterAtt▒
                              - 86.94% eprosima::fastrtps::rtps::StatefulWriter::send_periodic_heartbeat                                                              ▒
                                 - 86.41% eprosima::fastrtps::rtps::StatefulWriter::send_heartbeat_to_all_readers                                                     ▒
                                    - 84.36% eprosima::fastrtps::rtps::StatefulWriter::intraprocess_heartbeat                                                         ▒
                                       - 82.57% eprosima::fastrtps::rtps::RTPSDomainImpl::find_local_reader                                                           ▒
                                          - 70.10% eprosima::fastrtps::rtps::RTPSParticipantImpl::find_local_reader                                                   ▒
                                             - 47.28% eprosima::fastrtps::rtps::operator==                                                                            ▒
                                                  28.16% memcmp                                                                                                       ▒
                                                - 6.87% eprosima::fastrtps::rtps::operator==
```

So I try to change `heartbeatPeriod` as below config XML.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <profiles>
        <!-- Default publisher profile -->
        <publisher profile_name="topic_1" is_default_profile="true">
            <qos>
                <publishMode>
                    <kind>ASYNCHRONOUS</kind>
                </publishMode>
            </qos>
            <historyMemoryPolicy>PREALLOCATED_WITH_REALLOC</historyMemoryPolicy>
            <times> <!-- writerTimesType -->
                <initialHeartbeatDelay>
                    <sec>1</sec>
                    <nanosec>0</nanosec>
                </initialHeartbeatDelay>

                <heartbeatPeriod>
                    <sec>5</sec>
                    <nanosec>0</nanosec>
                </heartbeatPeriod>
            </times>
        </publisher>

        <!-- Request subscriber profile for services -->
        <subscriber profile_name="topic_1" is_default_profile="true">
            <times> <!-- readerTimesType -->
                <initialAcknackDelay>
                    <sec>0</sec>
                    <nanosec>70000000</nanosec>
                </initialAcknackDelay>

                <heartbeatResponseDelay>
                    <sec>0</sec>
                    <nanosec>30000000</nanosec>
                </heartbeatResponseDelay>
            </times>
            <historyMemoryPolicy>PREALLOCATED_WITH_REALLOC</historyMemoryPolicy>
        </subscriber>
    </profiles>
</dds>
```

And run this config file on both sides.   
```
$ export FASTRTPS_DEFAULT_PROFILES_FILE=/root/ros2_src_latest/pub_sub_config.xml
$ export RMW_FASTRTPS_USE_QOS_FROM_XML=1
$ export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
$ ros2 run test_multi_nodes_multi_pub_sub multi_nodes_multi_pub -t 30 -p 1
```

```
$ export FASTRTPS_DEFAULT_PROFILES_FILE=/root/ros2_src_latest/pub_sub_config.xml
$ export RMW_FASTRTPS_USE_QOS_FROM_XML=1
$ export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
$ build/test_multi_nodes_multi_pub_sub/multi_nodes_multi_sub -t 30 -s 10 -n1s1
```
Get CPU usage on subscriber  
19.36% (Before it is 98.82%)

**Comment by fujitatomoya** [comment] 2022-12-28 20:47
@Barry-Xu-2018 thanks for checking on this. `19.36%` is much better, but still not really cost effective, I understand that this is trading-off but can we also check other DDS implementation default setting for those parameters? i think that is going to be a baseline to compare the dormant performance.

**Comment by Barry-Xu-2018** [comment] 2023-01-04 08:07
![image](https://user-images.githubusercontent.com/43591679/210507866-7a36c6e4-49fe-402c-bb2b-bcb7da82ac98.png)

![image](https://user-images.githubusercontent.com/43591679/210508543-db5ec5b6-9a2e-4db9-9f3b-d011c3ca2464.png)

(192.168.0.143 is subscriber, 192.168.0.122 is publisher)
I analyzed cyclonedds case.  The period of heartbeat is 8 second by default for cyclonedds.  (8 second is the maximum heartbeat period in https://cyclonedds.io/docs/cyclonedds/latest/config/config_file_reference.html#cyclonedds-domain-internal-heartbeatinterval)

Found a different behavior. For cyclonedds, the heartbeat messages are sent each other between publisher and subscriber.  
But for fastdds (use default configuration), I only found the heartbeat messages are only sent from subscriber to publisher.  

I will change fastdds XML config to keep that fastdds configuration is the similar with cyclonedds.

**Comment by Barry-Xu-2018** [comment] 2023-01-05 08:57
> I will change fastdds XML config to keep that fastdds configuration is the similar with cyclonedds.  

After checking, except `heartbeatPeriod`, other items doesn't affect the result.   
After setting `heartbeatPeriod` to 8 second, the CPU usage decreases to 16.65% on subscriber (300 nodes). 

According to record RTPS packages, I find
### cyclonedds
- publisher (30 nodes, each node has a publisher corresponding to one topic)  
      
    Send heartbeat submessage every 8 second.  The `WriterEntityId` (built-in participation message writer)  in these heartbeat submessages are the same.   
    Except heartbeat submessage, RTPS package include other 2 submessage       
    ![image](https://user-images.githubusercontent.com/43591679/210719186-becddb1a-45dd-41b6-ba33-5e5ac4c3de3d.png)

    Send acknack submessage every 8 second. The `WriterEntityId` is the same as in the above heartbeat submessage. So this acknack is for built-in participation message writer in subscriber side. 
    ![image](https://user-images.githubusercontent.com/43591679/210720954-7903e939-1f14-4305-b5af-2f262e73bb61.png)

- subscriber (300 nodes, each node has a subscription. 10 subscriptions is corresponding to one topic)
    Send heartbeat submessage every 8 second.  The `WriterEntityId` (built-in participation message writer)  in these heartbeat submessages are the same.    
    Send acknack submessage every 8 second.  This acknack is for built-in participation message writer in publisher side. 

wireshark recorded file [cyclonedds.pcapng.zip](https://github.com/eProsima/Fast-DDS/files/10350350/cyclonedds.pcapng.zip)
(publisher on 192.168.0.122 and subscriber on 192.168.0.143)

So there are fewer packages sent between publisher and subscriber.

### fastdds

- publisher (30 nodes, each node has a publisher corresponding to one topic)  

   Not send heartbeat submessage. Almost all sent messages are acknack submessages and the `WriterEntityId` is application participation writer (not built-in participation writer).
   ![image](https://user-images.githubusercontent.com/43591679/210729847-fc804fe7-7683-484c-8f35-86b498448d45.png)
   A acknack submessage for a pair of `ReaderEntityId` and `WriterEntityId` is sent every 8 second since we set `heartbeatPeriod`.
   ![image](https://user-images.githubusercontent.com/43591679/210731381-a4a4b597-82d2-43ff-a42e-fd4dd348b3d4.png)

- subscriber (300 nodes, each node has a subscription. 10 subscriptions is corresponding to one topic)

   Almost all sent messages are heartbeat submessage.   
   ![image](https://user-images.githubusercontent.com/43591679/210732079-cf8d6ba4-30a5-4ed5-8e28-ae664e3baecc.png)
   
   For each `WriterEntityId`, heartbeat submessage is sent every 8 second. 
   ![image](https://user-images.githubusercontent.com/43591679/210732430-357339c7-7552-4d9b-9d94-1429062b5d68.png)

   wireshark recorded file [fastdds.zip](https://github.com/eProsima/Fast-DDS/files/10350599/fastdds.zip)

Based on the above result, I have some questions. 
1. According to my understanding, heartbeat submessage should be sent on publisher (writer) side. For fastdds, it is sent from subscriber. 
2. If no data is published, writer (publisher) should send heartbeat submessage periodically. For cyclonedds, it seems application writer doesn't send heartbeat. This behavior is correct ?
3. If no data is published, the specification (https://www.omg.org/spec/DDSI-RTPS) give an example  
     ![image](https://user-images.githubusercontent.com/43591679/210739091-349153db-3314-411b-a0af-446188c2e014.png)
     But, for fastrtps, the content of heartbeat submessage show some samples in cache to be sent.     
     ![image](https://user-images.githubusercontent.com/43591679/210740226-0988806b-c630-4c0b-b329-9c242f915064.png)

**Comment by Barry-Xu-2018** [comment] 2023-01-12 06:32
@MiguelCompany About the above question 1 and 3, what do you think ?

**Comment by fujitatomoya** [comment] 2023-01-12 23:17
Just want to clarify the status.

@MiguelCompany 

> The answer to both questions is the same. There are more DDS topics used under the hood in ROS 2.

this is issue and question for DDS but ROS 2, right? If i am not mistaken, this does not answer the questions?

@Barry-Xu-2018 

> According to my understanding, heartbeat submessage should be sent on publisher (writer) side. For fastdds, it is sent from subscriber.
> If no data is published, writer (publisher) should send heartbeat submessage periodically.

So Fast-DDS sends heartbeat submessages from subscription (DataReader), right? the question is that this is expected behavior or not? let's put the other dds implementation aside, probably we should see what is the correct behavior at 1st.

> If no data is published, the specification (https://www.omg.org/spec/DDSI-RTPS) give an example

you are suggesting above is NOT correct behavior, since this DDSI-RTPS specification example, right?

**Comment by MiguelCompany** [comment] 2023-01-13 06:25
@fujitatomoya 

> this is issue and question for DDS but ROS 2, right?

The reproducer mentioned in the description is built after ` source /opt/ros/rolling/setup.bash` and launched with `ros2 run`, so I'd say this issue is about Fast DDS on ROS 2.

> So Fast-DDS sends heartbeat submessages from subscription (DataReader), right?

No. Only DataWriters send heartbeat submessages.

> > If no data is published, the specification (https://www.omg.org/spec/DDSI-RTPS) give an example
> 
> you are suggesting above is NOT correct behavior, since this DDSI-RTPS specification example, right?

If no data has been published via a call to `DataWriter::write`, the writer might send a heartbeat as described by @Barry-Xu-2018  (first_seq = 1, last_seq = 0) when a DataReader is discovered. Heartbeats are periodically sent if there are changes in the history that have not yet been acknowledged, so for DataWriters on which nothing has been published, no heartbeats will be sent after the one I've just mentioned.

> Just want to clarify the status.

I hope this clarifies

**Comment by Barry-Xu-2018** [comment] 2023-01-13 07:15
@fujitatomoya 

> So Fast-DDS sends heartbeat submessages from subscription (DataReader), right? 

Yes. Based on wireshark display as the below

 

the question is that this is expected behavior or not? let's put the other dds implementation aside, probably we should see what is the correct behavior at 1st.

**Comment by MiguelCompany** [comment] 2023-01-13 07:40
> Based on wireshark recorded log, I find heartbeat submessage are all from subscriber side. So I ask above qeustions.

Bear in mind that a ROS 2 node without anything else has DataWriters being created under the hood. So a ROS 2 subscription has several DataWriters which are created before the user creates a subscription on the node

**Comment by Barry-Xu-2018** [comment] 2023-01-13 08:12
> Bear in mind that a ROS 2 node without anything else has DataWriters being created under the hood. So a ROS 2 subscription has several DataWriters which are created before the user creates a subscription on the node

Maybe I get it. Once a ROS2 node is created (user doesn't create publisher/subscription/service/client, etc), there are several Datawriters created. These Datawriter are for such as parameter service, etc.  
So these recorded heartbeat messages are from Datawriters on each node created for subscribers. For my test, I created many nodes as subscriber. These heartbeat messages are from these nodes (Not related to create subscription on each node).

**Comment by MiguelCompany** [comment] 2023-01-13 08:16
> Maybe I get it.

You got it!

**Comment by fujitatomoya** [comment] 2023-01-13 16:40
> The reproducer mentioned in the description is built after  source /opt/ros/rolling/setup.bash and launched with ros2 run, so I'd say this issue is about Fast DDS on ROS 2.

sorry i was mistaken, that means probably the difference could be come from implementation in ROS 2? we were actually seeing the huge difference against `rmw_cyclondds`, so that led me to think there could be DDS difference.

> Bear in mind that a ROS 2 node without anything else has DataWriters being created under the hood. So a ROS 2 subscription has several DataWriters which are created before the user creates a subscription on the node

right, this is different from each rmw implementation i guess, that could be leading the difference that we see.

> You got it!

we got it !

**Comment by fujitatomoya** [comment] 2023-01-13 16:42
Or what we need to improve is actually DDS aspect, so maybe having some example implemented by DDS, and then keep the discussion here?

**Comment by Barry-Xu-2018** [comment] 2023-01-15 02:47
@fujitatomoya 

Current difference between fastdds and cyclone dds is the number of datawriter on subscriber node side.  
The cyclonedds has only the one.  
A ROS2 node is corresponding to one participation. Each node for subscriber should have datawriter for certain functions such as parameters service. So the behavior of fastdds can be explained since there are many nodes. But cyclonedds has only one datawriter. I don't sure which codes of layer (rmw or dds) leads to this difference.  I will quickly check cyclonedds' code to try to find something.

**Comment by Barry-Xu-2018** [comment] 2023-01-17 12:26
> A ROS2 node is corresponding to one participation. Each node for subscriber should have datawriter for certain functions such as parameters service. 

According to DDSI-RTPS specification, 
![image](https://user-images.githubusercontent.com/43591679/212896964-e16f079e-7bff-4cb8-8a1e-1e4066d1802f.png)

If no message publishes, there is no heartbeat message. So these heartbeat message should not be from ROS2.  
I incline that these hearbeat messages are from datawrite for built-in topic.   
So it is related to DDS implementation (Not rmw layer).

**Comment by EduPonz** [comment] 2023-01-17 14:48
Hi @Barry-Xu-2018,

> A ROS2 node is corresponding to one participation

This is not necessary the case. The DDS DomainParticipant is held by the ROS 2 context. While it's true that most ROS 2 processes would only run one Node (thus having only one context), it is possible to group several nodes into the same process, thus sharing a context and therefore a single DomainParticipant. A more precise, although not entirely true statement is that normally a single ROS 2 process has a single DomainParticipant.

> If no message publishes, there is no heartbeat message. So these heartbeat message should not be from ROS2.
> I incline that these hearbeat messages are from datawrite for built-in topic.

It is important to understand that none of the HEARTBEAT messages (or any other messages for that matter) are directly from ROS 2, they all come from the underlying DDS entities.

There are two kind of builtin entities at play here:

* The DDS builtin entities, i.e. the writers and readers used by the DomainParticipants to perform the two discovery phases (PDP & EDP), and for the writer liveliness protocol (WLP), as well as those related to security certificates and documents exchange.
* The ROS 2 "builtin" entities. These correspond to the Node's parameter server, the ROS 2 discovery information distribution (`ros_discovery_info` topic), and other topics that ROS 2 creates under the hood and are different from the rclcpp user publication topics.

For instance, running a simple `ros2 run demo_nodes_cpp listener` will create DataWriters in all the following topics:

* ros_discovery_info
* rr/listener/describe_parametersReply
* rr/listener/get_parameter_typesReply
* rr/listener/get_parametersReply
* rr/listener/list_parametersReply
* rr/listener/set_parameters_atomicallyReply
* rr/listener/set_parametersReply
* rt/parameter_events
* rt/rosout

Those are all ROS 2 "builtin" DataWriters; mind that this is a subscription, so there are no rclcpp user publications here. These DataWriters are not RMW specific, you will find them no matter which implementation you use. Mind that reliable DataWriters will send HEARTBEATS if there is information to be shared with their corresponding DataReaders. More specifically, the `ros_discovery_info` has lots of updates as ROS 2 entities are created and discovered.

> So it is related to DDS implementation (Not rmw layer).

rmw_fastrtps_cpp is an adapter between ROS 2 and Fast DDS, but from the Fast DDS point of view, rmw_fastrtps_cpp is just another user. The fact that ROS 2 creates several DataWriters has nothing to do with the DDS implementation (Fast DDS) and all to do with the ROS 2 layers (rmw or otherwise). In fact, the rmw layer itself does not create entities on its own either (with the exception of those for `ros_discovery_info`, which are created on context initialization), only doing so when its user (RCL) commands so.

I'm afraid that without a complete wireshark capture started before any ROS 2 related process (including the ROS 2 Daemon), it is very difficult to address whether those HEARTBEAT messages are to be expected or not. Once we have that, we can address whether there is a miss-behaviour on Fast DDS itself, or if your observations arise from the use of Fast DDS in ROS 2 (rmw_fastrtps), or even upper the ROS 2 stack.

**Comment by fujitatomoya** [comment] 2023-01-17 22:10
> The cyclonedds has only the one.
> A ROS2 node is corresponding to one participation. Each node for subscriber should have datawriter for certain functions such as parameters service. So the behavior of fastdds can be explained since there are many nodes. But cyclonedds has only one datawriter. I don't sure which codes of layer (rmw or dds) leads to this difference. I will quickly check cyclonedds' code to try to find something.

I understand this is off topic from Fast-DDS, but for information and knowledge, would you share your thoughts and insights?
this could be really helpful for ROS 2 user why and which rmw implementation should be used for the application.

this is about how to bind DDS endpoints to ROS 2 entities, so platform or implementation difference exists for sure.

instead of having efficiency, this could be many downsides? for example QoS cannot be configured for each DataWriter and DataReader? anything else?

**Comment by fujitatomoya** [comment] 2023-01-17 22:12
@Barry-Xu-2018 according to https://github.com/eProsima/Fast-DDS/issues/3163#issuecomment-1385541014, probably we can rebase our test program for Fast-DDS to this issue? having ROS 2 stack giving us more complication, although this has been good discussion and information. what would you say?

**Comment by Barry-Xu-2018** [comment] 2023-01-18 03:12
@fujitatomoya 

> probably we can rebase our test program for Fast-DDS to this issue? having ROS 2 stack giving us more complication, although this has been good discussion and information. what would you say?  

Totally agree. I will rebase our test for Fast-DDS.

**Comment by Barry-Xu-2018** [comment] 2023-01-18 03:36
@EduPonz Thanks for the detailed explanation. It makes my understanding clearer.

**Comment by EduPonz** [comment] 2023-01-18 11:22
> I understand this is off topic from Fast-DDS, but for information and knowledge, would you share your thoughts and insights?

I run the same test yesterday with CycloneDDS and I could see the same DataWriters plus two other on topics `rq/listener/` (unfortunately, I've lost the precise names). @Barry-Xu-2018 how did you arrive to the conclusion that there is only one DataWriter when using CycloneDDS?

**Comment by EduPonz** [comment] 2023-01-18 13:37
> According to wireshark recorded (https://github.com/eProsima/Fast-DDS/files/10350350/cyclonedds.pcapng.zip attached in the above the comments), I can find heartbeat message are from one Datawriter (Please check heartbeat message from 192.168.0.143(subscriber) to 192.168.0.122(publisher)). But this cannot represent that there is only one Datawriter since no heartbeat message are sent if no message is sent in Datawriter.

The problem with that capture is that it's been taken once the application had started, so there is missing information on it. If you could provide a similar one but starting to capture before running anything ROS related that'd fantastic.

> BTW, is there any existing tool for fastdds to list all topic ? (Of cause, I can print all topic names while creating topic in fastdds)

I did this with wireshark, but in fact you can use [Fast DDS Monitor](https://fast-dds-monitor.readthedocs.io/en/latest/rst/user_manual/application_menu.html#hide-show-metatraffic), just make sure to [show metatraffic entities](https://fast-dds-monitor.readthedocs.io/en/latest/rst/user_manual/application_menu.html#hide-show-metatraffic). In fact, you can use Fast DDS monitoring for checking the DDS entities when using Cyclone DDS as well. I'm attaching a couple of captures using the listener from the talker listener/demo with both Fast DDS and CycloneDDS. There, you can see that they both create several ROS 2 "builtin" DataReaders and DataWriters (please omit the `_metatrafic_` DataWriter as it's not a real DataWriter but an entity created by the monitor to hold some data that it cannot place elsewhere).

##### Fast DDS
![fastdds_monitor_ros2_topics](https://user-images.githubusercontent.com/7962388/213183784-9ec01b78-76fb-44e5-8e8c-a9aec08e2965.png)

##### CycloneDDS
![cyclonedds_monitor_ros2_topics](https://user-images.githubusercontent.com/7962388/213184602-b5ba113d-292e-410d-8d14-54c1fa3f5d2f.png)

**Comment by Barry-Xu-2018** [comment] 2023-01-19 02:04
@EduPonz  

> The problem with that capture is that it's been taken once the application had started, so there is missing information on it. If you could provide a similar one but starting to capture before running anything ROS related that'd fantastic.

Yes. I find there is much more CPU usage on subscriber's side (many nodes and each node has one subscription) while subscription is connected to publish and no message is sent from publish.  
So after all connections are established, I run wireshark to capture the current messages between publish and subscriber.  So you cannot see the full message.  At this senior, I find the message of cyclonedds is less than fastdds.   

> I did this with wireshark, but in fact you can use [Fast DDS Monitor](https://fast-dds-monitor.readthedocs.io/en/latest/rst/user_manual/application_menu.html#hide-show-metatraffic), just make sure to [show metatraffic entities](https://fast-dds-monitor.readthedocs.io/en/latest/rst/user_manual/application_menu.html#hide-show-metatraffic). In fact, you can use Fast DDS monitoring for checking the DDS entities when using Cyclone DDS as well. I'm attaching a couple of captures using the listener from the talker listener/demo with both Fast DDS and CycloneDDS. There, you can see that they both create several ROS 2 "builtin" DataReaders and DataWriters (please omit the _metatrafic_ DataWriter as it's not a real DataWriter but an entity created by the monitor to hold some data that it cannot place elsewhere).

Thank you. I will try it.

**Comment by EduPonz** [comment] 2023-01-19 05:58
> Yes. I find there is much more CPU usage on subscriber's side (many nodes and each node has one subscription) while subscription is connected to publish and no message is sent from publish.

Would it be possible for you to send a capture over where you start capturing before running the experiment?

**Comment by Barry-Xu-2018** [comment] 2023-02-03 09:32
Sorry for late update information.    

After check rmw_fastrtps, a ros2 context is corresponding to a participant in fastdds.  
While a ros2 context is created, a publisher and a subscriber are also created under corresponding participant.  
A ros2 subscription is corresponding to a dataread in created subscriber.   

So `30 topic, 1 topic is corresponding to 10 nodes and each node has one subscription` in ros2 is equal to `1 participant, 1 subscriber, 300 datareaders, 10 datareaders is for 1 topic` in fastdds.   

According to this condition, prepare test code based on fastdds and test gets CPU usage about 0.4% (The scenario for no message sent). And no heartbeat message is sent based on wireshark captured result.   
Test code is put at https://github.com/Barry-Xu-2018/dds_multi_pub_multi_sub.git.  

So CPU consumption should be unrelated to fastdds.

**Comment by MiguelCompany** [comment] 2023-02-03 09:38
@fujitatomoya Do you think we can close this based on this last [comment](https://github.com/eProsima/Fast-DDS/issues/3163#issuecomment-1415474060) from @Barry-Xu-2018 ?

**Comment by fujitatomoya** [comment] 2023-02-03 17:17
> 30 topic, 1 topic is corresponding to 10 nodes and each node has one subscription

i do not really understand this configuration. can you describe the configuration?

- total we have 10 nodes? in single process space or different PID?
- and each node creates subscription, this is okay.
- 30 topics means, that is supposed to mean that each subscription subscribes 3 topics for each?
- no publisher???

I was thinking the case we are looking to check is,

- participants scales up to 1, 10, 100... with different process space.
- endpoints, either publisher or subscription 10 for each participant, those are on different topics.
- DataReader and DataWriter on each topic.
- all endpoints are connected but not transmitting the messages at all

maybe we have misunderstanding here? @Barry-Xu-2018

**Comment by Barry-Xu-2018** [comment] 2023-02-04 08:57
> 30 topic, 1 topic is corresponding to 10 nodes and each node has one subscription

This is a test condition (red frame in below) in the above description of this issue.   
![screenshot-github com-2023 02 04-16_09_41](https://user-images.githubusercontent.com/43591679/216756643-ca4e53d5-9c0e-4c21-9eae-fa00bc82a5f7.png)

> total we have 10 nodes? in single process space or different PID?

300 nodes in single process.

> 30 topics means, that is supposed to mean that each subscription subscribes 3 topics for each?

No. 30 nodes (each node has a subscriber) is corresponding to 1 topic.  

> no publisher???

No. I didn't describe publishers because we focus on checking subscriber side.  
Please check the description of this issue. In signal process, there are 30 nodes and each node has a publisher which is for one topic.  

> I was thinking the case we are looking to check is,
>
> - participants scales up to 1, 10, 100... with different process space.
> - endpoints, either publisher or subscription 10 for each participant, those are on different topics.
> - DataReader and DataWriter on each topic.
> - all endpoints are connected but not transmitting the messages at all

After checking the implementation of rmw_fastdds, the participant is corresponding to a context of ros2.   
So original ros2 test (use multi-nodes, but use default context) just uses a participant of fastdds.
Therefore, I didn't use multi-participant in my fastdds test code.   
Fastdds test code like the blow  
![image](https://user-images.githubusercontent.com/43591679/216758500-851c9eba-535f-45fa-85bb-56ea04e738a1.png)

**Comment by MiguelCompany** [comment] 2023-02-06 06:41
> So CPU consumption should be unrelated to fastdds.

I will proceed and close this issue based on this comment.

@fujitatomoya @Barry-Xu-2018 Feel free to reopen / open another issue if necessary

**Closed by MiguelCompany** 2023-02-06 06:41 UTC
