### ISSUE TITLE
HISTORY_DATASHARING_PAYLOADPOOL Error [11064]

### ISSUE THREAD

**Issue by pinqingchen** [eProsima/Fast-DDS#1883] opened 2021-04-03 12:30 UTC
Hi,I'm testing on fastdds2.3.0 version with an example generated by fastddsgen2.0.0 . It is work , when the publihser and the subscriber run at the local machine .But when it run at two different machines , the subscriber is crashed. The idl file just like follow:
struct ddsparam
{
	long long fromid;
	long long toid;
	long long paramid;
	long long mask;
	long long param[64];
};
## Expected Behavior

Actually,the example in folder 'Fast-DDS\examples\C++\HelloWorldExample' is work both local machine and different machines.
## Current Behavior

the fastddsgen2.0.0 example crashed with '[HISTORY_DATASHARING_PAYLOADPOOL Error] Failed to open segment fast_datasharing_01.0f.e6.00.90.62.08.32.01.00.00.00_0.0.1.3: ??????????? -> Function eprosima::fastrtps::rtps::ReaderPool::init_shared_memory ...'

## System information

- Fast-RTPS version: v2.3.0
- OS: Win10 vs2019
- Network interfaces: 169.254.192.251

**Comment by IkerLuengo** [comment] 2021-04-06 15:16
It looks like both machines are trying to communicate through datasharing when they cannot. We have some leads, but we will need some more information in order to progress with the issue:

- Are they physically different machines? Or are these virtual machines / containers on the same host?
- If they are VM / containers on the same host, which is the network configuration? (NAT, bridged, HOST,...)
- Does only the subscriber crash? Or the publisher too?

We also prepared a patch for FastDDS v2.3.0 to get some extra information about the datasharing ID (which is calculated from the machines' MAC addresses and is used to decide if datasharing communication should be used). You can find this patch attached to this comment. If you could apply it to FastDDS, recompile, and post here the resulting log errors for both the publisher and the subscriber, that would help us a lot.

[logtraces.patch.zip](https://github.com/eProsima/Fast-DDS/files/6265678/logtraces.patch.zip)

**Comment by pinqingchen** [comment] 2021-04-07 03:31
> It looks like both machines are trying to communicate through datasharing when they cannot. We have some leads, but we will need some more information in order to progress with the issue:
> 
> * Are they physically different machines? Or are these virtual machines / containers on the same host?
> * If they are VM / containers on the same host, which is the network configuration? (NAT, bridged, HOST,...)
> * Does only the subscriber crash? Or the publisher too?
> 
> We also prepared a patch for FastDDS v2.3.0 to get some extra information about the datasharing ID (which is calculated from the machines' MAC addresses and is used to decide if datasharing communication should be used). You can find this patch attached to this comment. If you could apply it to FastDDS, recompile, and post here the resulting log errors for both the publisher and the subscriber, that would help us a lot.
> 
> [logtraces.patch.zip](https://github.com/eProsima/Fast-DDS/files/6265678/logtraces.patch.zip)

There are two physical machines.One physical machines is installed with virtual machines , another is without. 

Both pulisher and subscriber are run in  physical machines, not run in virtual machines.The publisher run in physical machine with virtual machines installed. The subscriber run in physical machine without virtual machines installed.

Publisher internet physical information:
Description . . . . . . . . . . . : Realtek Gaming GbE Family Controller
Physical Address. . . . . . . . . :  B4-A9-FC-21-00-F9
DHCP Enabled. . . . . . . . . . . : Yes
Autoconfiguration Enabled . . . . : Yes
Link-local IPv6 Address . . . . . :fe80::b13c:317c:a556:c0fb%24(Preferred)
Autoconfiguration IPv4 Address. . : 169.254.192.251(Preferred)
Subnet Mask . . . . . . . . . . . :255.255.0.0

Subscriber internet physical information:
Description . . . . . . . . . . . : Intel(R) I210 Gigabit Network Connection
Physical Address. . . . . . . . . : 00-18-23-76-47-74
DHCP Enabled. . . . . . . . . . . : Yes
Autoconfiguration Enabled . . . . : Yes
Link-local IPv6 Address . . . . . : fe80::79cc:5a05:171a:28b6%11(Preferred)
Autoconfiguration IPv4 Address. . : 169.254.40.182(Preferred)
Subnet Mask . . . . . . . . . . . : 255.255.0.0

Pulisher is not crashed,and still waiting for subscriber. And using patch,log as follow:
Starting
2021-04-07 10:41:10.530 [UTILS Error] Adding MAC: 180:169:252:33:0:249: -> Function eprosima::Host::Host
2021-04-07 10:41:10.548 [UTILS Error] Computed ID: 213:151:82:88:248:216: -> Function eprosima::Host::Host
ddsparam DataWriter created.
ddsparam DataWriter waiting for DataReaders.
2021-04-07 10:41:10.628 [HISTORY_DATASHARING_LISTENER Error] Failed to open segment fast_datasharing_01.0f.42.1f.c8.12.23.f4.01.00.00.00_0.0.1.4: The system cannot find the file specified. -> Function eprosima::fastrtps::rtps::DataSharingNotification::open_and_init_notification
DataWriter unmatched.

Subscriber is crashed and exit. And using patch,log as follow:
Starting
2021-04-07 10:38:09.177 [UTILS Error] Adding MAC: 0:24:35:118:71:116: -> Function eprosima::Host::Host
2021-04-07 10:38:09.180 [UTILS Error] Adding MAC: 0:24:35:118:71:116: -> Function eprosima::Host::Host
2021-04-07 10:38:09.180 [UTILS Error] Computed ID: 183:74:93:184:21:47: -> Function eprosima::Host::Host
Waiting for Data, press Enter to stop the DataReader.
2021-04-07 10:40:49.634 [HISTORY_DATASHARING_PAYLOADPOOL Error] Failed to open segment fast_datasharing_01.0f.e6.00.98.4c.30.d7.01.00.00.00_0.0.1.3: The system cannot find the file specified. -> Function eprosima::fastrtps::rtps::ReaderPool::init_shared_memory

**Comment by IkerLuengo** [comment] 2021-04-07 09:19
Thank you @pinqingchen for the update, it was very informative. We thought the problem might be on the generation of IDs, but these traces confirm that the IDs are different for publisher and subscriber (as they should be in your use case). We tried reproducing the problem on our side, injecting computed IDs given in your traces, but everything worked as expected.

I prepared another patch with additional log traces, now focusing on the publisher-subscriber matching part. The idea is to find why they are considering that they can use data-sharing. It can be applied over the previous patch. If you could repeat the test and post the logs here, it will help us understand what is different about your case. If you could attach a network capture with the RTPS traffic on one of the machines, that would be fantastic. 

[logtraces2.patch.zip](https://github.com/eProsima/Fast-DDS/files/6270439/logtraces2.patch.zip)

Additionally, we recently merged #1845 fixing a bug on the ID generation algorithm. Looking at your traces, it looks like this is not your problem, but you could also try upgrading to the latest commit in `master` and retesting, just in case.

**Comment by pinqingchen** [comment] 2021-04-07 11:55
Hi @IkerLuengo,I try the latest commit in master.It's work!
Thanks ,nice job!

**Comment by EduPonz** [comment] 2021-04-08 06:57
I'll go ahead and close this. Feel free to re-open if the problem persists

**Closed by EduPonz** 2021-04-08 06:57 UTC
