### ISSUE TITLE
Sending protobuf serialization data may lead to data loss;()

### ISSUE THREAD

**Issue by wangzm-R** [eProsima/Fast-DDS#4887] opened 2024-06-03 09:00 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

If a ‘/0’ exists in the data, it is not truncated;
[modify code.txt](https://github.com/user-attachments/files/15531426/modify.code.txt)

### Current behavior

![企业微信截图_17049420717909](https://github.com/eProsima/Fast-DDS/assets/64530666/f23e49dd-7c66-454b-aaa4-69f446c44c36)

    code:
    BATMessage oMessage; //fastddsgen data
    BATRTTowerInfo oInfo; //protobuf data
    oMessage.set_timestamp(clock());
    std::string serialString;
    serialString = oInfo.SerializeAsString();
    oMessage.set_data(serialString);
    oMessage.set_datatype("BATRTTowerInfo");

m_data is Serialize to String data;
because ：
![image](https://github.com/eProsima/Fast-DDS/assets/64530666/52c1e8b6-5715-4f3c-81d4-1dba931e66b7)

Sending data is truncated

### Steps to reproduce

    code:
    BATMessage oMessage; //fastddsgen data
    BATRTTowerInfo oInfo; //protobuf data
    oMessage.set_timestamp(clock());
    std::string serialString;
    serialString = oInfo.SerializeAsString();
    oMessage.set_data(serialString);
    oMessage.set_datatype("BATRTTowerInfo");

### Fast DDS version/commit

fastdds 2.14.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64, Windows 10 Visual Studio 2019

### Transport layer

TCPv4

**Comment by wangzm-R** [comment] 2024-06-03 09:05
receive data is 
![企业微信截图_17049426033463](https://github.com/eProsima/Fast-DDS/assets/64530666/8b621461-2200-4262-b26c-68251ab22eed)

**Comment by EduPonz** [comment] 2024-06-03 09:13
I'm closing this as duplicate of #2919. Following that thread you'll end up on [this comment](https://github.com/eProsima/Fast-DDS/issues/2689#issuecomment-1132705252). The summary is that IDL 4.2 specifically states that strings cannot contain the `\0` character. That means that for sending byte-arrays, using string serialization is not suitable (see [here](https://github.com/eProsima/Fast-DDS/discussions/2919#discussioncomment-3381035)).

**Closed by EduPonz** 2024-06-03 09:13 UTC
Labels: triage
