### ISSUE TITLE
[15488] reader->get_unread_count() always returns 1 even without taking or reading opreration.

### ISSUE THREAD

**Issue by hehenihao** [eProsima/Fast-DDS#2941] opened 2022-09-03 05:25 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

reader->get_unread_count() should read the unread samples count.

### Current behavior

reader->get_unread_count() always returns 1

### Steps to reproduce

put a `return` in the `on_data_available` function before `take_next_sample`, show as following:
```c++
  void on_data_available(eprosima::fastdds::dds::DataReader *reader) override {

      if (zerocopy_ == false) {
        SampleInfo info;
        printf("----reader->get_unread_count(): %d\n", reader->get_unread_count());
        return;  // RETURN WITHOUT TAKING THE SAMPLE
        if (reader->take_next_sample(&msg_, &info) == ReturnCode_t::RETCODE_OK) {
          if (info.instance_state == ALIVE_INSTANCE_STATE) {
            samples_++;
          }
      }
}

```

### Fast DDS version/commit

2.4.1

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4, Shared Memory Transport (SHM), Data-sharing delivery

### Relevant log output

```shell
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
----reader->get_unread_count(): 1
```

**Comment by MiguelCompany** [comment] 2022-09-05 05:37
@hehenihao With the default QoS, this is expected behavior.

As the default HistoryQoS is KEEP_LAST with a depth of 1, with a non-keyed topic only the last received sample is kept on the reader's history.

This is why `get_unread_count()` always returns 1.

**Comment by MiguelCompany** [comment] 2022-09-06 05:32
Closing as duplicate of #2939

**Closed by MiguelCompany** 2022-09-06 05:32 UTC
