### ISSUE TITLE
1.10.0 Compile error following get started doc

### ISSUE THREAD

**Issue by wutianze** [eProsima/Fast-DDS#1247] opened 2020-06-02 14:17 UTC
Follow the steps in Docs » 1. Getting Started » 1.3. Writing a simple publisher and subscriber application and met an error when compiling. However, the video demo works well.

## Expected Behavior

compile pass

## Current Behavior

HelloWorldPublisher.cpp:41:5: error: ‘Topic’ does not name a type
   41 |     Topic* topic_;

## Steps to Reproduce
1. Install FastRTPS
2. Follow the Doc, build the project
3. Compile the publisher
4. Fail

## System information

-OS Ubuntu 18.04 & Ubuntu 20.04
-FastRTPS FastRTPS 1.10.0

**Comment by MiguelCompany** [comment] 2020-06-02 14:40
Please bear in mind that the latest documentation refers to the latest release (v2.0.0). If you are using a previous release, like 1.10.0, use that version of the docs (i.e. https://fast-dds.docs.eprosima.com/en/v1.10.0)

**Comment by MiguelCompany** [comment] 2020-06-02 14:42
Closing as duplicate of eProsima/Fast-RTPS-docs#157

**Closed by MiguelCompany** 2020-06-02 14:42 UTC
