### ISSUE TITLE
unable to transport image messages

### ISSUE THREAD

**Issue by christian-rauch** [eProsima/Fast-DDS#3651] opened 2023-02-15 14:54 UTC
I am unable to transport ROS image messages via the discovery server, while simple string messages such as those from the [ROS 2 Fast-DDS Discovery Server tutorial](https://fast-dds.docs.eprosima.com/en/latest/fastdds/ros2/discovery_server/ros2_discovery_server.html) work as expected.

In my setup there are two PCs (in the following called "server" and "client") with Ubuntu 20.04 and ROS2 rolling connected to a wired network, but in different subnets.

To reproduce:
1. Start the discovery server on the "server" (message producer):
    ```sh
    source /opt/ros/rolling/setup.bash
    fastdds discovery -i 0
    ```

2. Start an image producer on the "server":
    ```sh
    source /opt/ros/rolling/setup.bash
    export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    # set variable `IP`, e.g. for a single network interface
    export IP=$(hostname -I | awk '{print $1}')
    export ROS_DISCOVERY_SERVER="$IP:11811"
    ros2 run image_tools cam2image --ros-args -p burger_mode:=True
    ```

3. Start an image consumer on the "client":
    ```sh
    source /opt/ros/rolling/setup.bash
    export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    # set variable `IP` to the IP of the server 
    export ROS_DISCOVERY_SERVER="$IP:11811"
    ros2 run image_tools showimage
    ```

The `cam2image` node will continuously print an image index (`[cam2image]: Publishing image eProsima/Discovery-Server#1`) on the terminal. When I start the `showimage` on the client, I noticed that the publishing rate on the server drop significantly. No image messages arrive at the client, i.e. no images are shown via the `showimage` node. When I stop the `showimage` node again, the publishing rate (as indicated by the messages on the terminal) returns to normal.

Using `ros2 run demo_nodes_cpp talker` and `ros2 run demo_nodes_cpp listener` in place of `ros2 run image_tools cam2image` and `ros2 run image_tools showimage` works as expected in the same terminals with the same settings.

The dropped publishing rate of the image producer and the working example with the string message of the `demo_nodes_cpp` suggests that this is related to the message size.

**Comment by JLBuenoLopez-eProsima** [comment] 2023-07-04 06:14
Now that the issue is in Fast DDS repository, I am going to move it to the proper discussion forum according to [Fast DDS CONTRIBUTING guidelines](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues-and-support). 

I have tried to reproduce the issue with the latest ROS 2 Rolling docker container which has Fast DDS v2.10.1 installed and I have not seen the issue you are reporting. Maybe it has been solved since the issue was opened. I am proceed and close it but please feel free to reopen if you are still having issues.

**Closed by JLBuenoLopez-eProsima** 2023-07-04 06:14 UTC
