### ISSUE TITLE
Program infinitely hangs while generating random value on AMD Ryzen 3600.

### ISSUE THREAD

**Issue by Oscarchoi** [eProsima/Fast-DDS#2694] opened 2022-05-23 15:04 UTC
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The `RTPSParticipant` object is created immediately on AMD Ryzen 3600 hardware.

### Current behavior

While creating `RTPSParticipant` with `RTPSDomain::createParticipant(...)`, the program infinitely hangs on AMD Ryzen 5 3600 hardware. Line 107 of the code below is where the code hangs.
[https://github.com/eProsima/Fast-DDS/blob/6a978a70589074f700d9b7c00cbaf91ba43d5031/src/cpp/rtps/common/GuidUtils.hpp#L105-L107](https://github.com/eProsima/Fast-DDS/blob/6a978a70589074f700d9b7c00cbaf91ba43d5031/src/cpp/rtps/common/GuidUtils.hpp#L105-L107)

While investigating the issue, I found the following posts.
- [https://arstechnica.com/gadgets/2019/10/how-a-months-old-amd-microcode-bug-destroyed-my-weekend/](https://arstechnica.com/gadgets/2019/10/how-a-months-old-amd-microcode-bug-destroyed-my-weekend/)
- https://gitlab.com/gromacs/gromacs/-/issues/3855
- https://github.com/systemd/systemd/issues/11810
- https://github.com/systemd/systemd/issues/18184

According to the posts, the issue seems to be a bug due to a random number generator of AMD 3000 series CPUs.

### Steps to reproduce

The identical code block from the `RTPSDomain.cpp` reproduces  the identical issue on Ryzen 3600 cpu.
The program hangs infinitely on the line `uint16_trand_value = distribution(generator);`
```c++
#include <random>

int main() {
  std::random_device generator;
  std::uniform_int_distribution<uint16_t> distribution(0, std::numeric_limits<uint16_t>::max());
  uint16_t rand_value = distribution(generator);
}
```

### Fast DDS version/commit

Tested the codes in the version which ros2 foxy version depends on. The code remains in the latest branch, too.

tag: 2.1.x
commit: 4db32122183390f895138bd569c6fa847d80b2c7

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

I guess that adding `std::mt19937` generator could help to prevent the infinite hanging issue even in case that the `std::random_device` does not work properly (it may not guarantee the random performance of the case).

```cpp
#include <random>

int main() {
  std::random_device rd;
  std::mt19937 generator(rd());
  std::uniform_int_distribution<uint16_t> distribution(0, std::numeric_limits<uint16_t>::max());
  uint16_t rand_value = distribution(generator);
}
```

**Comment by MiguelCompany** [comment] 2022-05-24 06:01
@Oscarchoi Thank you for your report. 

I guess that adding `std::mt19937` will do no harm, especially when seeded by a `std::random_device`, so I opened PR #2695 with that fix.

Could you check on your side if that solves your issue?

**Comment by EduPonz** [comment] 2022-06-01 10:19
I'm gonna go ahead and close this issue as it was not caused by Fast DDS and has been solved in origin. For reference, #2695 can be used to cherry-pick the changes if needed. Thanks!

**Closed by EduPonz** 2022-06-01 10:19 UTC
Labels: wontfix
